#profiles
#spring.profiles.active=local
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
logging.charset.console=UTF-8
logging.charset.file=UTF-8

#logging
logging.level.org.springframework.boot.autoconfigure=ERROR

#Server
server.servlet.contextPath=/
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.enabled=true

server.session.timeout=1800
server.shutdown=graceful

#common
spring.http.encoding.enable=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true
spring.lifecycle.timeout-per-shutdown-phase=20s

#JSP View
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

#mybatis
mybatis.type-aliases-package=com.erns.coching/**/mapper/*.java
mybatis.mapper-locations=classpath:myBatis/mapper/**/*.xml
mybatis.config-location=classpath:myBatis/sql-mapper-config.xml

#rest-template
rest-template.max-connection-total=100
rest-template.max-connection-per-route=5
rest-template.read-timeout=5000
rest-template.connection-timeout=3000

#\uae30\ud0c0\u0083\u0080
jackson.default-property-inclusion=null


#Note : \ub85c\uceec\ub9cc \uc0ac\uc6a9\u008c
#For Dev(devtools)
spring.devtools.livereload.enabled=true
spring.web.resources.static-locations=file:src/main/resources/static/
spring.thymeleaf.cache=false
spring.freemarker.cache=false
spring.groovy.template.cache=false
spring.mustache.cache=false


###############################################################
#Tomcat AJP (Note:\ud658\uacbd\uc5d0 \ub530\ub77c \ubcc0\uacbd\ud544\uc694\u009a\u0094)
tomcat.ajp.enabled=false
tomcat.ajp.protocol=AJP/1.3
tomcat.ajp.port=8289

#\ub0b4\uc7a5 Tomcat (Note:\ud658\uacbd\uc5d0 \ub530\ub77c \ubcc0\uacbd\ud544\uc694\u009a\u0094)
server.port=8280
server.tomcat.max-connections=500
server.tomcat.threads.max=200
server.tomcat.uri-encoding=UTF-8
server.base.url=http://localhost:8280
server.error.path=/coching-bo/error-404

#Log (Note:\ud658\uacbd\uc5d0 \ub530\ub77c \ubcc0\uacbd\ud544\uc694\u009a\u0094)
logging.config=classpath:logback-local.xml

#DB (Note:\ud658\uacbd\uc5d0 \ub530\ub77c \ubcc0\uacbd\ud544\uc694\u009a\u0094)
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=1800000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-test-query=select now()

#DB \uc811\uc18d\uc815\ubcf4 (Note:\ud658\uacbd\uc5d0 \ub530\ub77c \ubcc0\uacbd\ud544\uc694\u009a\u0094)
spring.datasource.url=jdbc:log4jdbc:postgresql://192.168.1.104/coching_dev
spring.datasource.username=coching
spring.datasource.password=coching2024!@

#JWE
jwe.iss=https://admin.coching.co.kr
jwe.private-key.path=classpath:/key/erns_coching_private_key.pem
jwe.public-key.path=classpath:/key/erns_coching_public_key.pem
jwe.access-expire-time=1800000
jwe.refresh-expire-time=7200000
jwe.refresh-remain-expire-time=604800000

#\uc5d0\ubbac\ub808\uc774\ud130
jwe.emulator-pc-iss=https://www.coching.co.kr
jwe.emulator-prt-iss=https://partner.coching.co.kr
jwe.emulator-access-expire-time=600000
jwe.emulator-refresh-expire-time=1800000
server.pc.base.url=http://cochingadmdev.erns.co.kr 
server.user.base.url=http://cochingdev.erns.co.kr 
server.ptn.base.url=http://cochingprtdev.erns.co.kr 


#FILE repo (Note:\ud658\uacbd\uc5d0 \ub530\ub77c \ubcc0\uacbd\ud544\uc694\u009a\u0094)
system.file.uploadpath=C:\\data//local/upload/files

#roadAddress
address.confmkey=U01TX0FVVEgyMDIyMTIzMDEwMjI1MDExMzM4ODM=


#batch
batch.generate-locale-json=true
batch.reset-coching-raw-index=false
batch.reset-coching-tv-index=false
batch.send-coching-mail=false
batch.send-mail-max-cnt=100
batch.pdf-info-convert=false
batch.remove-preview-files=false
batch.create-profile-img=true
batch.create-profile-max-cnt=100

#erns-es-api
es.search.api.isDummyTest=false
es.search.protocal=http
es.search.host=192.168.0.101
es.search.port=28090

#mail sender
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=coching@coching.co.kr
spring.mail.password=kykdmbjtcpwndoxc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
#spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

#backup mail sender
mail.backup.host=192.168.1.104
mail.backup.port=25
mail.backup.username=
mail.backup.password=
mail.backup.auth=false
mail.backup.starttls.enable=true
mail.backup.ssl.enable=false

#mail info
coching.mail.sender=coching@coching.co.kr
coching.mail.toMail=dsnam@erns.co.kr
coching.mail.isTest=true

#aes keys
aes.key.image=COCHING20250101_WOW

#Youtube API KEY
youtube.api.key=AIzaSyCIdUFqYEBFmdhoJvEIrWfPkh81xFJVtow

#prsc AI DEMO
prsc.ai.demo.api.isDummyTest=false
prsc.ai.demo.api.protocal=http
prsc.ai.demo.api.host=192.168.0.101
prsc.ai.demo.api.port=28632