  DROP TABLE "APPS"."T_SHORT_URL_INF";

  CREATE TABLE "APPS"."T_SHORT_URL_INF"
   (	"URL_ID" VARCHAR2(200 BYTE) NOT NULL ENABLE,
      "URL" VARCHAR2(4000 BYTE),
      "METHOD" VARCHAR2(20 BYTE),
      "PARAM_JSON" VARCHAR2(4000 BYTE),
      "TOKEN" VARCHAR2(200 BYTE),

      "RGTR" NUMBER(8,0),
      "RGT_DTTM" DATE DEFAULT SYSDATE,
      "HITS" NUMBER(8,0),
      "LAST_DTTM" DATE DEFAULT SYSDATE,
	 CONSTRAINT "IX_T_SHORT_URL_INF_P" PRIMARY KEY ("URL_ID")
  USING INDEX TABLESPACE "TSD_APPS_DEFT"  ENABLE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_SHORT_URL_INF"."URL_ID" IS 'URL ID';
   COMMENT ON COLUMN "APPS"."T_SHORT_URL_INF"."URL" IS 'URL';
   COMMENT ON COLUMN "APPS"."T_SHORT_URL_INF"."METHOD" IS '전송방식';
   COMMENT ON COLUMN "APPS"."T_SHORT_URL_INF"."PARAM_JSON" IS '파라미터JSON';
   COMMENT ON COLUMN "APPS"."T_SHORT_URL_INF"."TOKEN" IS '토큰';

   COMMENT ON COLUMN "APPS"."T_SHORT_URL_INF"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_SHORT_URL_INF"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_SHORT_URL_INF"."HITS" IS '접근 클릭수';
   COMMENT ON COLUMN "APPS"."T_SHORT_URL_INF"."LAST_DTTM" IS '최근사용일';
   COMMENT ON TABLE "APPS"."T_SHORT_URL_INF"  IS '단축 URL 정보';


CREATE TABLE T_CNTRC_LOG
(
    LOG_SEQ           NUMBER(8,0)    NOT NULL,
    CNTRC_SEQ         NUMBER(8,0)    NOT NULL,
    CNTRC_LOG_TYPE    VARCHAR(50)    NOT NULL,
    REMARK            VARCHAR2(2000 BYTE) NULL,
    RGTR              NUMBER(8,0)    NOT NULL,
    RGT_DTTM          DATE           NOT NULL,
    CONSTRAINT IX_T_CNTRC_LOG_P PRIMARY KEY (LOG_SEQ)
USING INDEX TABLESPACE "TSD_APPS_DEFT"  ENABLE
) TABLESPACE "TSD_APPS_DEFT" ;

-- 테이블 Comment 설정 SQL - T_CNTRC_LOG
COMMENT ON TABLE T_CNTRC_LOG IS '계약 전체 로그';

-- 컬럼 Comment 설정 SQL - T_CNTRC_LOG.LOG_SEQ
COMMENT ON COLUMN T_CNTRC_LOG.LOG_SEQ IS '로그 SEQ';

-- 컬럼 Comment 설정 SQL - T_CNTRC_LOG.CNTRC_SEQ
COMMENT ON COLUMN T_CNTRC_LOG.CNTRC_SEQ IS '계약 SEQ';

-- 컬럼 Comment 설정 SQL - T_CNTRC_LOG.CNTRC_LOG_TYPE
COMMENT ON COLUMN T_CNTRC_LOG.CNTRC_LOG_TYPE IS '계약 상태';

-- 컬럼 Comment 설정 SQL - T_CNTRC_LOG.REMARK
COMMENT ON COLUMN T_CNTRC_LOG.REMARK IS '비고(수정된 계약 사항 저장)';

-- 컬럼 Comment 설정 SQL - T_CNTRC_LOG.RGTR
COMMENT ON COLUMN T_CNTRC_LOG.RGTR IS '등록자';

-- 컬럼 Comment 설정 SQL - T_CNTRC_LOG.RGT_DTTM
COMMENT ON COLUMN T_CNTRC_LOG.RGT_DTTM IS '등록일';

CREATE INDEX IX_T_CNTRC_LOG_N01 ON T_CNTRC_LOG (CNTRC_SEQ)
TABLESPACE "TSD_APPS_DEFT" ;
