--------------------------------------------------------
--  파일이 생성됨 - 금요일-12월-22-2023
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table t_memb_admin_inf
--------------------------------------------------------

  CREATE TABLE "APPS"."t_memb_admin_inf"
   (	"A_MEMB_SEQ" NUMBER(8,0),
	"A_MEMB_ID" VARCHAR2(50 BYTE),
	"AUTH_TYPE" VARCHAR2(20 BYTE),
	"A_MEMB_PSWD" VARCHAR2(300 BYTE),
	"A_MEMB_SALT" VARCHAR2(100 BYTE),
	"A_MEMB_NAME" VARCHAR2(50 BYTE),
	"A_MEMB_PHONE" VARCHAR2(50 BYTE),
	"A_MEMB_EMAIL" VARCHAR2(50 BYTE),
	"A_PSWD_CHNG_DTTM" DATE,
	"A_PSWD_ERR_COUNT" NUMBER(8,0),
	"A_PSWD_INIT_YN" CHAR(1 BYTE) DEFAULT 'N',
	"A_PSWD_EXP_DTTM" DATE,
	"USE_YN" CHAR(1 BYTE) DEFAULT 'Y',
	"A_RCT_ACS_DTTM" DATE,
	"A_RCT_ACS_IP" VARCHAR2(100 BYTE),
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE DEFAULT SYSDATE,
	"CHNR" NUMBER(8,0),
	"CHNG_DTTM" DATE DEFAULT SYSDATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."t_memb_admin_inf"."A_MEMB_SEQ" IS '사용자SEQ';
   COMMENT ON COLUMN "APPS"."t_memb_admin_inf"."A_MEMB_ID" IS '사용자 ID';
   COMMENT ON COLUMN "APPS"."t_memb_admin_inf"."AUTH_TYPE" IS '권한 타입';
   COMMENT ON COLUMN "APPS"."t_memb_admin_inf"."A_MEMB_PSWD" IS '비밀번호';
   COMMENT ON COLUMN "APPS"."t_memb_admin_inf"."A_MEMB_SALT" IS '암호화키값';
   COMMENT ON COLUMN "APPS"."t_memb_admin_inf"."A_MEMB_NAME" IS '이름';
   COMMENT ON COLUMN "APPS"."t_memb_admin_inf"."A_MEMB_PHONE" IS '연락처';
   COMMENT ON COLUMN "APPS"."t_memb_admin_inf"."A_MEMB_EMAIL" IS '이메일';
   COMMENT ON COLUMN "APPS"."t_memb_admin_inf"."A_PSWD_CHNG_DTTM" IS '비밀번호 변경일';
   COMMENT ON COLUMN "APPS"."t_memb_admin_inf"."A_PSWD_ERR_COUNT" IS '비밀번호 틀린 횟수';
   COMMENT ON COLUMN "APPS"."t_memb_admin_inf"."A_PSWD_INIT_YN" IS '비밀번호 초기화여부';
   COMMENT ON COLUMN "APPS"."t_memb_admin_inf"."A_PSWD_EXP_DTTM" IS '비밀번호 만료일';
   COMMENT ON COLUMN "APPS"."t_memb_admin_inf"."USE_YN" IS '사용여부';
   COMMENT ON COLUMN "APPS"."t_memb_admin_inf"."A_RCT_ACS_DTTM" IS '최근 접속일';
   COMMENT ON COLUMN "APPS"."t_memb_admin_inf"."A_RCT_ACS_IP" IS '최근 접속IP';
   COMMENT ON COLUMN "APPS"."t_memb_admin_inf"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."t_memb_admin_inf"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."t_memb_admin_inf"."CHNR" IS '수정자';
   COMMENT ON COLUMN "APPS"."t_memb_admin_inf"."CHNG_DTTM" IS '수정일';
   COMMENT ON TABLE "APPS"."t_memb_admin_inf"  IS '관리자';
--------------------------------------------------------
--  DDL for Table T__MEMB_LOG_H
--------------------------------------------------------

  CREATE TABLE "APPS"."T__MEMB_LOG_H"
   (	"LOG_DATE" CHAR(23 BYTE) DEFAULT 'SYSDATE',
	"MEMB_SEQ" NUMBER(8,0),
	"LOG_TYPE" VARCHAR2(30 BYTE),
	"SITE_TYPE" VARCHAR2(30 BYTE),
	"MEMB_ID" VARCHAR2(50 BYTE),
	"MEMB_IP" VARCHAR2(50 BYTE),
	"LOG_JSON" VARCHAR2(4000 BYTE)
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T__MEMB_LOG_H"."LOG_DATE" IS '로그시간';
   COMMENT ON COLUMN "APPS"."T__MEMB_LOG_H"."MEMB_SEQ" IS '사용자SEQ';
   COMMENT ON COLUMN "APPS"."T__MEMB_LOG_H"."LOG_TYPE" IS '로그타입';
   COMMENT ON COLUMN "APPS"."T__MEMB_LOG_H"."SITE_TYPE" IS '사이트구분. 관리자/사용자/PC';
   COMMENT ON COLUMN "APPS"."T__MEMB_LOG_H"."MEMB_ID" IS '사용자ID';
   COMMENT ON COLUMN "APPS"."T__MEMB_LOG_H"."MEMB_IP" IS '사용자IP';
   COMMENT ON COLUMN "APPS"."T__MEMB_LOG_H"."LOG_JSON" IS '로그. 파라미터,결과값 JSON (사용자로그)';
   COMMENT ON TABLE "APPS"."T__MEMB_LOG_H"  IS '사용자로그';
--------------------------------------------------------
--  DDL for Table T_TOKEN_ACCESS
--------------------------------------------------------

  CREATE TABLE "APPS"."T_TOKEN_ACCESS"
   (	"TOKEN" VARCHAR2(2000 BYTE),
	"SITE_TYPE" VARCHAR2(30 BYTE),
	"DEVICE_KEY" VARCHAR2(500 BYTE),
	"MEMB_SEQ" NUMBER(8,0),
	"EXP_DATE" DATE,
	"RGT_DTTM" DATE DEFAULT SYSDATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_TOKEN_ACCESS"."TOKEN" IS '토큰';
   COMMENT ON COLUMN "APPS"."T_TOKEN_ACCESS"."SITE_TYPE" IS '사이트구분';
   COMMENT ON COLUMN "APPS"."T_TOKEN_ACCESS"."DEVICE_KEY" IS '디바이스KEY';
   COMMENT ON COLUMN "APPS"."T_TOKEN_ACCESS"."MEMB_SEQ" IS '사용자 아이디';
   COMMENT ON COLUMN "APPS"."T_TOKEN_ACCESS"."EXP_DATE" IS '만료기간';
   COMMENT ON COLUMN "APPS"."T_TOKEN_ACCESS"."RGT_DTTM" IS '등록일';
   COMMENT ON TABLE "APPS"."T_TOKEN_ACCESS"  IS '인증토큰 JWE-Access 허용토큰';
--------------------------------------------------------
--  DDL for Table T__TOKEN_BLACKLIST
--------------------------------------------------------

  CREATE TABLE "APPS"."T__TOKEN_BLACKLIST"
   (	"TOKEN" VARCHAR2(2000 BYTE),
	"SITE_TYPE" VARCHAR2(30 BYTE),
	"DEVICE_KEY" VARCHAR2(500 BYTE),
	"MEMB_SEQ" NUMBER(8,0),
	"EXP_DATE" DATE,
	"RGT_DTTM" DATE DEFAULT SYSDATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T__TOKEN_BLACKLIST"."TOKEN" IS '토큰';
   COMMENT ON COLUMN "APPS"."T__TOKEN_BLACKLIST"."SITE_TYPE" IS '사이트구분';
   COMMENT ON COLUMN "APPS"."T__TOKEN_BLACKLIST"."DEVICE_KEY" IS '디바이스KEY';
   COMMENT ON COLUMN "APPS"."T__TOKEN_BLACKLIST"."MEMB_SEQ" IS '사용자아이디';
   COMMENT ON COLUMN "APPS"."T__TOKEN_BLACKLIST"."EXP_DATE" IS '만료기간';
   COMMENT ON COLUMN "APPS"."T__TOKEN_BLACKLIST"."RGT_DTTM" IS '등록일시';
   COMMENT ON TABLE "APPS"."T__TOKEN_BLACKLIST"  IS '인증토큰 JWE-Access 차단토큰';
--------------------------------------------------------
--  DDL for Table T_TOKEN_REFRESH
--------------------------------------------------------

  CREATE TABLE "APPS"."T_TOKEN_REFRESH"
   (	"TOKEN" VARCHAR2(2000 BYTE),
	"SITE_TYPE" VARCHAR2(30 BYTE),
	"DEVICE_KEY" VARCHAR2(500 BYTE),
	"MEMB_SEQ" NUMBER(8,0),
	"EXP_DATE" DATE,
	"RGT_DTTM" DATE DEFAULT SYSDATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_TOKEN_REFRESH"."TOKEN" IS '토큰';
   COMMENT ON COLUMN "APPS"."T_TOKEN_REFRESH"."SITE_TYPE" IS '사이트구분';
   COMMENT ON COLUMN "APPS"."T_TOKEN_REFRESH"."DEVICE_KEY" IS '디바이스KEY';
   COMMENT ON COLUMN "APPS"."T_TOKEN_REFRESH"."MEMB_SEQ" IS '사용자 아이디';
   COMMENT ON COLUMN "APPS"."T_TOKEN_REFRESH"."EXP_DATE" IS '만료기간';
   COMMENT ON COLUMN "APPS"."T_TOKEN_REFRESH"."RGT_DTTM" IS '등록일시';
   COMMENT ON TABLE "APPS"."T_TOKEN_REFRESH"  IS '인증토큰 JWE-Refresh 허용토큰';
--------------------------------------------------------
--  DDL for Table T_ACCOUNT_INF
--------------------------------------------------------

  CREATE TABLE "APPS"."T_ACCOUNT_INF"
   (	"ACCOUNT_SEQ" NUMBER(8,0),
	"COMP_SEQ" NUMBER(8,0),
	"BANK_CODE" VARCHAR2(3 BYTE),
    "SUB_ID" VARCHAR2(50 BYTE),
	"ACCOUNT_NUM" VARCHAR2(20 BYTE),
	"CURRENCY_TYPE" VARCHAR2(10 BYTE),
	"ACCOUNT_HOLDER" VARCHAR2(20 BYTE),
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE,
	"CHNR" NUMBER(8,0),
	"CHNG_DTTM" DATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_ACCOUNT_INF"."ACCOUNT_SEQ" IS '계좌 SEQ';
   COMMENT ON COLUMN "APPS"."T_ACCOUNT_INF"."COMP_SEQ" IS '기업SEQ';
   COMMENT ON COLUMN "APPS"."T_ACCOUNT_INF"."SUB_ID" IS '서브몰 ID';
   COMMENT ON COLUMN "APPS"."T_ACCOUNT_INF"."BANK_CODE" IS '은행코드';
   COMMENT ON COLUMN "APPS"."T_ACCOUNT_INF"."ACCOUNT_NUM" IS '계좌번호';
   COMMENT ON COLUMN "APPS"."T_ACCOUNT_INF"."CURRENCY_TYPE" IS '통화 타입';
   COMMENT ON COLUMN "APPS"."T_ACCOUNT_INF"."ACCOUNT_HOLDER" IS '예금주';
   COMMENT ON COLUMN "APPS"."T_ACCOUNT_INF"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_ACCOUNT_INF"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_ACCOUNT_INF"."CHNR" IS '수정자';
   COMMENT ON COLUMN "APPS"."T_ACCOUNT_INF"."CHNG_DTTM" IS '수정일';
   COMMENT ON TABLE "APPS"."T_ACCOUNT_INF"  IS '기업 계좌정보';
--------------------------------------------------------
--  DDL for Table T_API_PROC_H
--------------------------------------------------------

  CREATE TABLE "APPS"."T_API_PROC_H"
   (	"API_LOG_SEQ" NUMBER(38,0),
	"MEMB_SEQ" NUMBER(8,0),
	"QUERY_STR" VARCHAR2(500 BYTE),
	"PROC_STATUS" CHAR(1 BYTE),
	"PROC_MSG" VARCHAR2(1000 BYTE),
	"PROC_TYPE" VARCHAR2(20 BYTE),
	"RGT_DTTM" DATE DEFAULT SYSDATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_API_PROC_H"."API_LOG_SEQ" IS 'API로그SEQ';
   COMMENT ON COLUMN "APPS"."T_API_PROC_H"."MEMB_SEQ" IS '사용자SEQ';
   COMMENT ON COLUMN "APPS"."T_API_PROC_H"."QUERY_STR" IS '요청파라미터';
   COMMENT ON COLUMN "APPS"."T_API_PROC_H"."PROC_STATUS" IS '처리상태. 처리상태 (요청:0, 응답:1, 에러:E)';
   COMMENT ON COLUMN "APPS"."T_API_PROC_H"."PROC_MSG" IS '처리메세지';
   COMMENT ON COLUMN "APPS"."T_API_PROC_H"."PROC_TYPE" IS 'API 실행사이트';
   COMMENT ON COLUMN "APPS"."T_API_PROC_H"."RGT_DTTM" IS '등록일';
   COMMENT ON TABLE "APPS"."T_API_PROC_H"  IS 'API 요청 로그';
--------------------------------------------------------
--  DDL for Table T_BANNER_INF
--------------------------------------------------------

  CREATE TABLE "APPS"."T_BANNER_INF"
   (	"BANNER_SEQ" NUMBER(8,0),
	"BANNER_MST_CD" VARCHAR2(30 BYTE),
	"BANNER_NAME" VARCHAR2(200 BYTE),
	"FROM_DATE" CHAR(10 BYTE),
	"TO_DATE" CHAR(10 BYTE),
	"BANNER_DESC" VARCHAR2(500 BYTE),
	"BANNER_URL" VARCHAR2(100 BYTE),
	"BANNER_WIDTH" NUMBER(8,0),
	"BANNER_HEIGHT" NUMBER(8,0),
	"CLICKS" NUMBER(8,0),
	"SORT_ORD" NUMBER(8,0),
	"USE_YN" CHAR(1 BYTE) DEFAULT 'Y',
	"DEL_YN" CHAR(1 BYTE) DEFAULT 'N',
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE DEFAULT SYSDATE,
	"CHNR" NUMBER(8,0),
	"CHNG_DTTM" DATE DEFAULT SYSDATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_BANNER_INF"."BANNER_SEQ" IS '배너SEQ';
   COMMENT ON COLUMN "APPS"."T_BANNER_INF"."BANNER_MST_CD" IS '배너마스터CD';
   COMMENT ON COLUMN "APPS"."T_BANNER_INF"."BANNER_NAME" IS '배너명';
   COMMENT ON COLUMN "APPS"."T_BANNER_INF"."FROM_DATE" IS '시작일. 배너게시 시작일';
   COMMENT ON COLUMN "APPS"."T_BANNER_INF"."TO_DATE" IS '종료일. 배너게시 종료일';
   COMMENT ON COLUMN "APPS"."T_BANNER_INF"."BANNER_DESC" IS '배너설명';
   COMMENT ON COLUMN "APPS"."T_BANNER_INF"."BANNER_URL" IS '배너이동URL';
   COMMENT ON COLUMN "APPS"."T_BANNER_INF"."BANNER_WIDTH" IS '가로길이';
   COMMENT ON COLUMN "APPS"."T_BANNER_INF"."BANNER_HEIGHT" IS '새로길이';
   COMMENT ON COLUMN "APPS"."T_BANNER_INF"."CLICKS" IS '클릭횟수';
   COMMENT ON COLUMN "APPS"."T_BANNER_INF"."SORT_ORD" IS '정렬순서';
   COMMENT ON COLUMN "APPS"."T_BANNER_INF"."USE_YN" IS '사용여부';
   COMMENT ON COLUMN "APPS"."T_BANNER_INF"."DEL_YN" IS '삭제여부';
   COMMENT ON COLUMN "APPS"."T_BANNER_INF"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_BANNER_INF"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_BANNER_INF"."CHNR" IS '수정자';
   COMMENT ON COLUMN "APPS"."T_BANNER_INF"."CHNG_DTTM" IS '수정일';
   COMMENT ON TABLE "APPS"."T_BANNER_INF"  IS '배너';
--------------------------------------------------------
--  DDL for Table T_BANNER_MST_INF
--------------------------------------------------------

  CREATE TABLE "APPS"."T_BANNER_MST_INF"
   (	"BANNER_MST_CD" VARCHAR2(30 BYTE),
	"BANNER_TYPE" VARCHAR2(30 BYTE),
	"BANNER_MST_NAME" VARCHAR2(30 BYTE),
	"BANNER_MST_DESC" VARCHAR2(200 BYTE),
	"USE_YN" CHAR(1 BYTE) DEFAULT 'Y',
	"WIDTH" NUMBER(8,0),
	"HEIGHT" NUMBER(8,0),
	"PREVIEW_URL" VARCHAR2(500 BYTE),
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE DEFAULT SYSDATE,
	"CHNR" NUMBER(8,0),
	"CHNG_DTTM" DATE DEFAULT SYSDATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_BANNER_MST_INF"."BANNER_MST_CD" IS '배너마스터CD';
   COMMENT ON COLUMN "APPS"."T_BANNER_MST_INF"."BANNER_TYPE" IS '배너 종류. 앱/웹 구분';
   COMMENT ON COLUMN "APPS"."T_BANNER_MST_INF"."BANNER_MST_NAME" IS '배너마스터명';
   COMMENT ON COLUMN "APPS"."T_BANNER_MST_INF"."BANNER_MST_DESC" IS '배너마스터설명';
   COMMENT ON COLUMN "APPS"."T_BANNER_MST_INF"."USE_YN" IS '사용여부';
   COMMENT ON COLUMN "APPS"."T_BANNER_MST_INF"."WIDTH" IS '가로길이';
   COMMENT ON COLUMN "APPS"."T_BANNER_MST_INF"."HEIGHT" IS '세로길이';
   COMMENT ON COLUMN "APPS"."T_BANNER_MST_INF"."PREVIEW_URL" IS '미리보기URL';
   COMMENT ON COLUMN "APPS"."T_BANNER_MST_INF"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_BANNER_MST_INF"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_BANNER_MST_INF"."CHNR" IS '수정자';
   COMMENT ON COLUMN "APPS"."T_BANNER_MST_INF"."CHNG_DTTM" IS '수정일';
   COMMENT ON TABLE "APPS"."T_BANNER_MST_INF"  IS '배너마스터';
--------------------------------------------------------
--  DDL for Table T_BIN_MST
--------------------------------------------------------

  CREATE TABLE "APPS"."T_BIN_MST"
   (	"BIN_SEQ" NUMBER(8,0),
	"COMP_SEQ" NUMBER(8,0),
	"BIN_NAME" VARCHAR2(200 BYTE),
	"START_SCTN1" VARCHAR2(4 BYTE),
	"START_SCTN2" VARCHAR2(4 BYTE),
	"START_SCTN3" VARCHAR2(4 BYTE),
	"START_SCTN4" VARCHAR2(4 BYTE),
	"END_SCTN1" VARCHAR2(4 BYTE),
	"END_SCTN2" VARCHAR2(4 BYTE),
	"END_SCTN3" VARCHAR2(4 BYTE),
	"END_SCTN4" VARCHAR2(4 BYTE),
	"FROM_DATE" CHAR(10 BYTE),
	"TO_DATE" CHAR(10 BYTE),
	"USE_YN" CHAR(1 BYTE) DEFAULT 'Y',
	"DEL_YN" CHAR(1 BYTE) DEFAULT 'N',
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE,
	"CHNR" NUMBER(8,0),
	"CHNG_DTTM" DATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_BIN_MST"."BIN_SEQ" IS 'BIN SEQ';
   COMMENT ON COLUMN "APPS"."T_BIN_MST"."COMP_SEQ" IS '기업SEQ';
   COMMENT ON COLUMN "APPS"."T_BIN_MST"."BIN_NAME" IS 'BIN 명칭';
   COMMENT ON COLUMN "APPS"."T_BIN_MST"."START_SCTN1" IS '시작 구간1';
   COMMENT ON COLUMN "APPS"."T_BIN_MST"."START_SCTN2" IS '시작 구간2';
   COMMENT ON COLUMN "APPS"."T_BIN_MST"."START_SCTN3" IS '시작 구간3';
   COMMENT ON COLUMN "APPS"."T_BIN_MST"."START_SCTN4" IS '시작 구간4';
   COMMENT ON COLUMN "APPS"."T_BIN_MST"."END_SCTN1" IS '종료 구간1';
   COMMENT ON COLUMN "APPS"."T_BIN_MST"."END_SCTN2" IS '종료 구간2';
   COMMENT ON COLUMN "APPS"."T_BIN_MST"."END_SCTN3" IS '종료 구간3';
   COMMENT ON COLUMN "APPS"."T_BIN_MST"."END_SCTN4" IS '종료 구간4';
   COMMENT ON COLUMN "APPS"."T_BIN_MST"."FROM_DATE" IS '적용시작날짜';
   COMMENT ON COLUMN "APPS"."T_BIN_MST"."TO_DATE" IS '적용종료날짜';
   COMMENT ON COLUMN "APPS"."T_BIN_MST"."USE_YN" IS '사용유무';
   COMMENT ON COLUMN "APPS"."T_BIN_MST"."DEL_YN" IS '삭제유무';
   COMMENT ON COLUMN "APPS"."T_BIN_MST"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_BIN_MST"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_BIN_MST"."CHNR" IS '수정자';
   COMMENT ON COLUMN "APPS"."T_BIN_MST"."CHNG_DTTM" IS '수정일';
   COMMENT ON TABLE "APPS"."T_BIN_MST"  IS 'BIN 관리';
--------------------------------------------------------
--  DDL for Table T_BOARD_CMT_INF
--------------------------------------------------------

  CREATE TABLE "APPS"."T_BOARD_CMT_INF"
   (	"BOARD_CMT_SEQ" NUMBER(8,0),
	"BOARD_SEQ" NUMBER(8,0),
	"WRITER" VARCHAR2(50 BYTE),
	"CONTENT" VARCHAR2(4000 BYTE),
	"DEL_YN" CHAR(1 BYTE) DEFAULT 'N',
	"ADMIN_DEL_CD" VARCHAR2(50 BYTE) DEFAULT 'N',
	"ADMIN_DEL_RSN" VARCHAR2(1000 BYTE),
	"ORG_SEQ" NUMBER(8,0),
	"SORT_ORD" NUMBER(8,0),
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE DEFAULT SYSDATE,
	"CHNR" NUMBER(8,0),
	"CHNG_DTTM" DATE DEFAULT SYSDATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_BOARD_CMT_INF"."BOARD_CMT_SEQ" IS '댓글SEQ';
   COMMENT ON COLUMN "APPS"."T_BOARD_CMT_INF"."BOARD_SEQ" IS '게시글SEQ';
   COMMENT ON COLUMN "APPS"."T_BOARD_CMT_INF"."WRITER" IS '작상자';
   COMMENT ON COLUMN "APPS"."T_BOARD_CMT_INF"."CONTENT" IS '내용';
   COMMENT ON COLUMN "APPS"."T_BOARD_CMT_INF"."DEL_YN" IS '삭제여부';
   COMMENT ON COLUMN "APPS"."T_BOARD_CMT_INF"."ADMIN_DEL_CD" IS '관리자삭제';
   COMMENT ON COLUMN "APPS"."T_BOARD_CMT_INF"."ADMIN_DEL_RSN" IS '관리자삭제사유';
   COMMENT ON COLUMN "APPS"."T_BOARD_CMT_INF"."ORG_SEQ" IS '그룹SEQ';
   COMMENT ON COLUMN "APPS"."T_BOARD_CMT_INF"."SORT_ORD" IS '정렬순서';
   COMMENT ON COLUMN "APPS"."T_BOARD_CMT_INF"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_BOARD_CMT_INF"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_BOARD_CMT_INF"."CHNR" IS '수정자';
   COMMENT ON COLUMN "APPS"."T_BOARD_CMT_INF"."CHNG_DTTM" IS '수정일';
   COMMENT ON TABLE "APPS"."T_BOARD_CMT_INF"  IS '댓글';
--------------------------------------------------------
--  DDL for Table T_BOARD_INF
--------------------------------------------------------

  CREATE TABLE "APPS"."T_BOARD_INF"
   (	"BOARD_SEQ" NUMBER(8,0),
	"BOARD_MST_ID" VARCHAR2(30 BYTE),
	"CATE_CD" VARCHAR2(30 BYTE),
	"TITLE" VARCHAR2(200 BYTE),
	"CONTENT" CLOB,
	"WRITER" VARCHAR2(50 BYTE),
	"ORG_SEQ" NUMBER(8,0),
	"SORT_ORD" NUMBER(8,0),
	"DEL_YN" CHAR(1 BYTE) DEFAULT 'N',
	"ADMIN_DEL_CD" VARCHAR2(30 BYTE),
	"ADMIN_DEL_RSN" VARCHAR2(1000 BYTE),
	"VIEWS" NUMBER(8,0),
	"FROM_DATE" CHAR(10 BYTE),
	"TO_DATE" CHAR(10 BYTE),
	"FIX_YN" CHAR(1 BYTE) DEFAULT 'N',
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE DEFAULT SYSDATE,
	"CHNR" NUMBER(8,0),
	"CHNG_DTTM" DATE DEFAULT SYSDATE
   ) TABLESPACE "TSD_APPS_DEFT"
 LOB ("CONTENT") STORE AS SECUREFILE (
  TABLESPACE "TSD_APPS_DEFT" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "APPS"."T_BOARD_INF"."BOARD_SEQ" IS '게시글 SEQ';
   COMMENT ON COLUMN "APPS"."T_BOARD_INF"."BOARD_MST_ID" IS '게시판마스터 ID';
   COMMENT ON COLUMN "APPS"."T_BOARD_INF"."CATE_CD" IS '게시판카테고리CD';
   COMMENT ON COLUMN "APPS"."T_BOARD_INF"."TITLE" IS '제목';
   COMMENT ON COLUMN "APPS"."T_BOARD_INF"."CONTENT" IS '내용';
   COMMENT ON COLUMN "APPS"."T_BOARD_INF"."WRITER" IS '작성자';
   COMMENT ON COLUMN "APPS"."T_BOARD_INF"."ORG_SEQ" IS '그룹SEQ';
   COMMENT ON COLUMN "APPS"."T_BOARD_INF"."SORT_ORD" IS '정렬순서';
   COMMENT ON COLUMN "APPS"."T_BOARD_INF"."DEL_YN" IS '삭제여부';
   COMMENT ON COLUMN "APPS"."T_BOARD_INF"."ADMIN_DEL_CD" IS '관리자삭제';
   COMMENT ON COLUMN "APPS"."T_BOARD_INF"."ADMIN_DEL_RSN" IS '관리자삭제사유';
   COMMENT ON COLUMN "APPS"."T_BOARD_INF"."VIEWS" IS '조회수';
   COMMENT ON COLUMN "APPS"."T_BOARD_INF"."FROM_DATE" IS '시작일. 게시 시작일';
   COMMENT ON COLUMN "APPS"."T_BOARD_INF"."TO_DATE" IS '종료일. 게시 종료일';
   COMMENT ON COLUMN "APPS"."T_BOARD_INF"."FIX_YN" IS '고정여부';
   COMMENT ON COLUMN "APPS"."T_BOARD_INF"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_BOARD_INF"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_BOARD_INF"."CHNR" IS '수정자';
   COMMENT ON COLUMN "APPS"."T_BOARD_INF"."CHNG_DTTM" IS '수정일';
   COMMENT ON TABLE "APPS"."T_BOARD_INF"  IS '게시글';
--------------------------------------------------------
--  DDL for Table T_BOARD_MST_INF
--------------------------------------------------------

  CREATE TABLE "APPS"."T_BOARD_MST_INF"
   (	"BOARD_MST_ID" VARCHAR2(30 BYTE),
	"BOARD_NAME" VARCHAR2(50 BYTE),
	"BOARD_TYPE" VARCHAR2(30 BYTE),
	"BOARD_DESC" VARCHAR2(200 BYTE),
	"USE_YN" CHAR(1 BYTE) DEFAULT 'Y',
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE DEFAULT SYSDATE,
	"CHNR" NUMBER(8,0),
	"CHNG_DTTM" DATE DEFAULT SYSDATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_BOARD_MST_INF"."BOARD_MST_ID" IS '게시판마스터ID';
   COMMENT ON COLUMN "APPS"."T_BOARD_MST_INF"."BOARD_NAME" IS '게시판명';
   COMMENT ON COLUMN "APPS"."T_BOARD_MST_INF"."BOARD_TYPE" IS '게시판타입';
   COMMENT ON COLUMN "APPS"."T_BOARD_MST_INF"."BOARD_DESC" IS '게시판설명';
   COMMENT ON COLUMN "APPS"."T_BOARD_MST_INF"."USE_YN" IS '사용여부';
   COMMENT ON COLUMN "APPS"."T_BOARD_MST_INF"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_BOARD_MST_INF"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_BOARD_MST_INF"."CHNR" IS '수정자';
   COMMENT ON COLUMN "APPS"."T_BOARD_MST_INF"."CHNG_DTTM" IS '수정일';
   COMMENT ON TABLE "APPS"."T_BOARD_MST_INF"  IS '게시판 마스터';
--------------------------------------------------------
--  DDL for Table T_BOARD_OPT_INF
--------------------------------------------------------

  CREATE TABLE "APPS"."T_BOARD_OPT_INF"
   (	"BOARD_MST_ID" VARCHAR2(30 BYTE),
	"LIST_CNT" NUMBER(8,0),
	"FILE_ADD_CNT" NUMBER(8,0),
	"FILE_EXT_EXP" VARCHAR2(1000 BYTE),
	"CATE_CD" VARCHAR2(30 BYTE)
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_BOARD_OPT_INF"."BOARD_MST_ID" IS '게시판마스터ID';
   COMMENT ON COLUMN "APPS"."T_BOARD_OPT_INF"."LIST_CNT" IS '목록 길이. 목록길이 설정';
   COMMENT ON COLUMN "APPS"."T_BOARD_OPT_INF"."FILE_ADD_CNT" IS '첨부파일 수';
   COMMENT ON COLUMN "APPS"."T_BOARD_OPT_INF"."FILE_EXT_EXP" IS '파일확장자. 첨부가능한 파일종류';
   COMMENT ON COLUMN "APPS"."T_BOARD_OPT_INF"."CATE_CD" IS '게시판카테고리CD';
   COMMENT ON TABLE "APPS"."T_BOARD_OPT_INF"  IS '게시판 옵션';
--------------------------------------------------------
--  DDL for Table T_CNTRC_INF
--------------------------------------------------------

  CREATE TABLE "APPS"."T_CNTRC_INF"
   (	"DETAIL_SEQ" NUMBER(8,0),
	"CNTRC_SEQ" NUMBER(8,0),
	"CNTRC_NAME" VARCHAR2(200 BYTE),
	"SALES_COMP" NUMBER(8,0),
	"PURCHASE_COMP" NUMBER(8,0),
	"SALES_MEMB" NUMBER(8,0),
	"PURCHASE_MEMB" NUMBER(8,0),
	"CURRENCY_TYPE" VARCHAR2(20 BYTE),
	"FULL_PAY_YN" CHAR(1 BYTE) DEFAULT 'N',
	"FILES_DATA" VARCHAR2(1000 BYTE),
	"SALES_SIGN_ID" VARCHAR2(200 BYTE),
	"PURCHASE_SIGN_ID" VARCHAR2(200 BYTE)
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_CNTRC_INF"."DETAIL_SEQ" IS '상세 SEQ';
   COMMENT ON COLUMN "APPS"."T_CNTRC_INF"."CNTRC_SEQ" IS '계약 SEQ';
   COMMENT ON COLUMN "APPS"."T_CNTRC_INF"."CNTRC_NAME" IS '계약명';
   COMMENT ON COLUMN "APPS"."T_CNTRC_INF"."SALES_COMP" IS '판매기업 SEQ';
   COMMENT ON COLUMN "APPS"."T_CNTRC_INF"."PURCHASE_COMP" IS '구매기업 SEQ';
   COMMENT ON COLUMN "APPS"."T_CNTRC_INF"."SALES_MEMB" IS '판매기업 담당자 SEQ';
   COMMENT ON COLUMN "APPS"."T_CNTRC_INF"."PURCHASE_MEMB" IS '구매기업 담당자 SEQ';
   COMMENT ON COLUMN "APPS"."T_CNTRC_INF"."CURRENCY_TYPE" IS '통화 구분';
   COMMENT ON COLUMN "APPS"."T_CNTRC_INF"."FULL_PAY_YN" IS '전액 결제 여부';
   COMMENT ON COLUMN "APPS"."T_CNTRC_INF"."FILES_DATA" IS '첨부파일 데이터';
   COMMENT ON COLUMN "APPS"."T_CNTRC_INF"."SALES_SIGN_ID" IS '판매기업 서명 파일 id';
   COMMENT ON COLUMN "APPS"."T_CNTRC_INF"."PURCHASE_SIGN_ID" IS '구매기업 서명 파일id';
   COMMENT ON TABLE "APPS"."T_CNTRC_INF"  IS '계약 상세정보';
--------------------------------------------------------
--  DDL for Table T_CNTRC_LOG
--------------------------------------------------------

  CREATE TABLE "APPS"."T_CNTRC_LOG"
   (	"LOG_SEQ" NUMBER(8,0),
	"CNTRC_SEQ" NUMBER(8,0),
	"CNTRC_LOG_TYPE" VARCHAR2(50 BYTE),
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_CNTRC_LOG"."LOG_SEQ" IS '로그 SEQ';
   COMMENT ON COLUMN "APPS"."T_CNTRC_LOG"."CNTRC_SEQ" IS '계약 SEQ';
   COMMENT ON COLUMN "APPS"."T_CNTRC_LOG"."CNTRC_LOG_TYPE" IS '계약 상태';
   COMMENT ON COLUMN "APPS"."T_CNTRC_LOG"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_CNTRC_LOG"."RGT_DTTM" IS '등록일';
   COMMENT ON TABLE "APPS"."T_CNTRC_LOG"  IS '계약 전체 로그';
--------------------------------------------------------
--  DDL for Table T_CNTRC_MST
--------------------------------------------------------

  CREATE TABLE "APPS"."T_CNTRC_MST"
   (	"CNTRC_SEQ" NUMBER(8,0),
	"CNTRC_STATUS" VARCHAR2(20 BYTE),
	"DEL_YN" CHAR(1 BYTE) DEFAULT 'N',
	"TOT_PRICE" VARCHAR2(20 BYTE),
	"CARD_PRICE" VARCHAR2(20 BYTE),
	"CARD_FEE_RATE" VARCHAR2(20 BYTE),
	"PG_FEE_RATE" VARCHAR2(20 BYTE),
	"NICE_FEE_RATE" VARCHAR2(20 BYTE),
	"VAT_FEE_RATE" VARCHAR2(20 BYTE),
	"CARD_FEE" VARCHAR2(20 BYTE),
	"PG_FEE" VARCHAR2(20 BYTE),
	"NICE_FEE" VARCHAR2(20 BYTE),
	"VAT_FEE" VARCHAR2(20 BYTE),
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE,
	"CHNR" NUMBER(8,0),
	"CHNG_DTTM" DATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_CNTRC_MST"."CNTRC_SEQ" IS '계약 SEQ';
   COMMENT ON COLUMN "APPS"."T_CNTRC_MST"."CNTRC_STATUS" IS '계약 상태';
   COMMENT ON COLUMN "APPS"."T_CNTRC_MST"."DEL_YN" IS '삭제여부';
   COMMENT ON COLUMN "APPS"."T_CNTRC_MST"."TOT_PRICE" IS '총 금액';
   COMMENT ON COLUMN "APPS"."T_CNTRC_MST"."CARD_PRICE" IS '카드 결제금액';
   COMMENT ON COLUMN "APPS"."T_CNTRC_MST"."CARD_FEE_RATE" IS '카드사 수수료율';
   COMMENT ON COLUMN "APPS"."T_CNTRC_MST"."PG_FEE_RATE" IS 'PG사 수수료율';
   COMMENT ON COLUMN "APPS"."T_CNTRC_MST"."NICE_FEE_RATE" IS '운영사 수수료율';
   COMMENT ON COLUMN "APPS"."T_CNTRC_MST"."VAT_FEE_RATE" IS '서비스 수수료율';
   COMMENT ON COLUMN "APPS"."T_CNTRC_MST"."CARD_FEE" IS '카드사 수수료';
   COMMENT ON COLUMN "APPS"."T_CNTRC_MST"."PG_FEE" IS 'PG사 수수료';
   COMMENT ON COLUMN "APPS"."T_CNTRC_MST"."NICE_FEE" IS '운영사 수수료';
   COMMENT ON COLUMN "APPS"."T_CNTRC_MST"."VAT_FEE" IS '서비스 수수료';
   COMMENT ON COLUMN "APPS"."T_CNTRC_MST"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_CNTRC_MST"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_CNTRC_MST"."CHNR" IS '수정자';
   COMMENT ON COLUMN "APPS"."T_CNTRC_MST"."CHNG_DTTM" IS '수정일';
   COMMENT ON TABLE "APPS"."T_CNTRC_MST"  IS '계약정보';
--------------------------------------------------------
--  DDL for Table T_CNTRC_PAYMENT
--------------------------------------------------------

  CREATE TABLE "APPS"."T_CNTRC_PAYMENT"
   (	"PAYMENT_SEQ" NUMBER(8,0),
	"CNTRC_SEQ" NUMBER(8,0),
	"MID" VARCHAR2(10 BYTE),
	"TID" VARCHAR2(30 BYTE),
	"MOID" VARCHAR2(64 BYTE),
	"PRICE" VARCHAR2(12 BYTE),
	"AUTH_CODE" VARCHAR2(30 BYTE),
	"AUTH_DATE" VARCHAR2(12 BYTE),
	"ACQU_CARD_CODE" VARCHAR2(4 BYTE),
	"ACQU_CARD_NAME" VARCHAR2(20 BYTE),
	"CARD_NO" VARCHAR2(20 BYTE),
	"CARD_CODE" VARCHAR2(4 BYTE),
	"CARD_NAME" VARCHAR2(20 BYTE),
	"CARD_QUOTA" VARCHAR2(2 BYTE),
	"CARD_TYPE" CHAR(1 BYTE),
	"CC_PART" CHAR(1 BYTE),
	"CARD_INTEREST" CHAR(1 BYTE),
	"REMARKS" VARCHAR2(500 BYTE),
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT"."PAYMENT_SEQ" IS '결제 SEQ';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT"."CNTRC_SEQ" IS '계약 SEQ';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT"."MID" IS 'MID';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT"."TID" IS '거래번호';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT"."MOID" IS '주문번호';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT"."PRICE" IS '총 결제금액';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT"."AUTH_CODE" IS '승인번호';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT"."AUTH_DATE" IS '승인일자';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT"."ACQU_CARD_CODE" IS '매입사 카드코드';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT"."ACQU_CARD_NAME" IS '매입사 카드사명';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT"."CARD_NO" IS '카드번호';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT"."CARD_CODE" IS '카드사코드';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT"."CARD_NAME" IS '카드사명';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT"."CARD_QUOTA" IS '할부개월';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT"."CARD_TYPE" IS '카드타입. (0: 신용카드 / 1: 체크카드)';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT"."CC_PART" IS '부분취소 가능여부. (0 : 불가능 / 1 : 가능)';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT"."CARD_INTEREST" IS '무이자 여부. (0: 이자 / 1: 무이자)';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT"."REMARKS" IS '정보전달용 여분필드';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT"."RGT_DTTM" IS '등록일';
   COMMENT ON TABLE "APPS"."T_CNTRC_PAYMENT"  IS '계약 결제 정보';
--------------------------------------------------------
--  DDL for Table T_CNTRC_PAYMENT_CANCEL
--------------------------------------------------------

  CREATE TABLE "APPS"."T_CNTRC_PAYMENT_CANCEL"
   (	"PAY_CANCEL_SEQ" NUMBER(8,0),
	"CNTRC_SEQ" NUMBER(8,0),
	"CANCEL_AMT" VARCHAR2(12 BYTE),
	"MID" VARCHAR2(10 BYTE),
	"MOID" VARCHAR2(64 BYTE),
	"PAY_METHOD" VARCHAR2(10 BYTE),
	"TID" VARCHAR2(30 BYTE),
	"CANCEL_NUM" VARCHAR2(8 BYTE),
    "CANCEL_DATE" VARCHAR2(8 BYTE),
    "CANCEL_TIME" VARCHAR2(6 BYTE),
	"REMARKS" VARCHAR2(500 BYTE),
	"RGT_DTTM" DATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT_CANCEL"."PAY_CANCEL_SEQ" IS '결제 취소 SEQ';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT_CANCEL"."CNTRC_SEQ" IS '계약 SEQ';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT_CANCEL"."CANCEL_AMT" IS '취소금액';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT_CANCEL"."MID" IS '상점 ID';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT_CANCEL"."MOID" IS '주문번호';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT_CANCEL"."PAY_METHOD" IS '결제수단 코드';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT_CANCEL"."TID" IS '거래번호';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT_CANCEL"."CANCEL_NUM" IS '취소번호';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT_CANCEL"."CANCEL_DATE" IS '취소일자';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT_CANCEL"."CANCEL_TIME" IS '취소시간';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT_CANCEL"."REMARKS" IS '정보전달용 여분필드';
   COMMENT ON COLUMN "APPS"."T_CNTRC_PAYMENT_CANCEL"."RGT_DTTM" IS '등록일';
   COMMENT ON TABLE "APPS"."T_CNTRC_PAYMENT_CANCEL"  IS '계약 결제 취소';
--------------------------------------------------------
--  DDL for Table T_CNTRC_SETTLE
--------------------------------------------------------

  CREATE TABLE "APPS"."T_CNTRC_SETTLE"
   (	"SETTLE_SEQ" NUMBER(8,0),
	"CNTRC_SEQ" NUMBER(8,0),
	"SETTLE_STATUS" VARCHAR2(20 BYTE),
	"MID" VARCHAR2(10 BYTE),
	"SUB_ID" VARCHAR2(50 BYTE),
	"PRICE" VARCHAR2(14 BYTE),
	"DUP_CHK_YN" CHAR(1 BYTE),
	"REQ_SEQ" VARCHAR2(20 BYTE),
	"SETTLE_DT" DATE,
	"RGT_DTTM" DATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_CNTRC_SETTLE"."SETTLE_SEQ" IS '지급 SEQ';
   COMMENT ON COLUMN "APPS"."T_CNTRC_SETTLE"."CNTRC_SEQ" IS '계약 SEQ';
   COMMENT ON COLUMN "APPS"."T_CNTRC_SETTLE"."SETTLE_STATUS" IS '지급 상태';
   COMMENT ON COLUMN "APPS"."T_CNTRC_SETTLE"."MID" IS 'MID';
   COMMENT ON COLUMN "APPS"."T_CNTRC_SETTLE"."SUB_ID" IS '서브 ID';
   COMMENT ON COLUMN "APPS"."T_CNTRC_SETTLE"."PRICE" IS '요청금액';
   COMMENT ON COLUMN "APPS"."T_CNTRC_SETTLE"."DUP_CHK_YN" IS '중복체크여부. Y/N';
   COMMENT ON COLUMN "APPS"."T_CNTRC_SETTLE"."REQ_SEQ" IS '요청 SEQ';
   COMMENT ON COLUMN "APPS"."T_CNTRC_SETTLE"."SETTLE_DT" IS '지급일';
   COMMENT ON COLUMN "APPS"."T_CNTRC_SETTLE"."RGT_DTTM" IS '등록일';
   COMMENT ON TABLE "APPS"."T_CNTRC_SETTLE"  IS '계약 지급 대행';
--------------------------------------------------------
--  DDL for Table T_CNTRC_SIGN_LOG
--------------------------------------------------------

  CREATE TABLE "APPS"."T_CNTRC_SIGN_LOG"
   (	"SIGN_SEQ" NUMBER(8,0),
	"CNTRC_SEQ" NUMBER(8,0),
	"COMPANY_TYPE" VARCHAR2(20 BYTE),
	"FILE_ID" VARCHAR2(200 BYTE),
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_CNTRC_SIGN_LOG"."SIGN_SEQ" IS '서명 SEQ';
   COMMENT ON COLUMN "APPS"."T_CNTRC_SIGN_LOG"."CNTRC_SEQ" IS '계약 SEQ';
   COMMENT ON COLUMN "APPS"."T_CNTRC_SIGN_LOG"."COMPANY_TYPE" IS '판매기업 구매기업 구분';
   COMMENT ON COLUMN "APPS"."T_CNTRC_SIGN_LOG"."FILE_ID" IS '파일 ID';
   COMMENT ON COLUMN "APPS"."T_CNTRC_SIGN_LOG"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_CNTRC_SIGN_LOG"."RGT_DTTM" IS '등록일';
   COMMENT ON TABLE "APPS"."T_CNTRC_SIGN_LOG"  IS '서명 로그';
--------------------------------------------------------
--  DDL for Table T_CODE_INF
--------------------------------------------------------

  CREATE TABLE "APPS"."T_CODE_INF"
   (	"CODE" VARCHAR2(30 BYTE),
	"GRP_CODE" VARCHAR2(30 BYTE),
	"CODE_NAME" VARCHAR2(100 BYTE),
	"ETC1" VARCHAR2(100 BYTE),
	"ETC2" VARCHAR2(100 BYTE),
	"ETC3" VARCHAR2(300 BYTE),
	"ETC4" VARCHAR2(100 BYTE),
	"ETC5" VARCHAR2(200 BYTE),
	"ETC_CMMT" VARCHAR2(200 BYTE),
	"REMARKS" VARCHAR2(1000 BYTE),
	"CODE_DESC" VARCHAR2(1000 BYTE),
	"SORT_ORD" NUMBER(8,0),
	"USE_YN" CHAR(1 CHAR) DEFAULT 'Y',
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE DEFAULT SYSDATE,
	"CHNR" NUMBER(8,0),
	"CHNG_DTTM" DATE DEFAULT SYSDATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_CODE_INF"."CODE" IS '코드';
   COMMENT ON COLUMN "APPS"."T_CODE_INF"."GRP_CODE" IS '그룹코드';
   COMMENT ON COLUMN "APPS"."T_CODE_INF"."CODE_NAME" IS '코드명';
   COMMENT ON COLUMN "APPS"."T_CODE_INF"."ETC1" IS 'ETC1';
   COMMENT ON COLUMN "APPS"."T_CODE_INF"."ETC2" IS 'ETC2';
   COMMENT ON COLUMN "APPS"."T_CODE_INF"."ETC3" IS 'ETC3';
   COMMENT ON COLUMN "APPS"."T_CODE_INF"."ETC4" IS 'ETC4';
   COMMENT ON COLUMN "APPS"."T_CODE_INF"."ETC5" IS 'ETC5';
   COMMENT ON COLUMN "APPS"."T_CODE_INF"."ETC_CMMT" IS 'ETC_CMMT';
   COMMENT ON COLUMN "APPS"."T_CODE_INF"."REMARKS" IS '비고';
   COMMENT ON COLUMN "APPS"."T_CODE_INF"."CODE_DESC" IS '코드설명';
   COMMENT ON COLUMN "APPS"."T_CODE_INF"."SORT_ORD" IS '정렬순서';
   COMMENT ON COLUMN "APPS"."T_CODE_INF"."USE_YN" IS '사용여부';
   COMMENT ON COLUMN "APPS"."T_CODE_INF"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_CODE_INF"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_CODE_INF"."CHNR" IS '수정자';
   COMMENT ON COLUMN "APPS"."T_CODE_INF"."CHNG_DTTM" IS '수정일';
   COMMENT ON TABLE "APPS"."T_CODE_INF"  IS '코드';
--------------------------------------------------------
--  DDL for Table T_CODE_MST_INF
--------------------------------------------------------

  CREATE TABLE "APPS"."T_CODE_MST_INF"
   (	"GRP_CODE" VARCHAR2(30 BYTE),
	"GRP_CODE_NAME" VARCHAR2(50 BYTE),
	"CODE_DESC" VARCHAR2(200 BYTE),
	"ETC_CMMT" VARCHAR2(20 BYTE) DEFAULT NULL,
	"USE_YN" CHAR(1 BYTE) DEFAULT 'Y',
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE DEFAULT SYSDATE,
	"CHNR" NUMBER(8,0),
	"CHNG_DTTM" DATE DEFAULT SYSDATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_CODE_MST_INF"."GRP_CODE" IS '그룹코드';
   COMMENT ON COLUMN "APPS"."T_CODE_MST_INF"."GRP_CODE_NAME" IS '그룹코드명';
   COMMENT ON COLUMN "APPS"."T_CODE_MST_INF"."CODE_DESC" IS '그룹코드설명';
   COMMENT ON COLUMN "APPS"."T_CODE_MST_INF"."ETC_CMMT" IS '기타코드설명';
   COMMENT ON COLUMN "APPS"."T_CODE_MST_INF"."USE_YN" IS '사용여부';
   COMMENT ON COLUMN "APPS"."T_CODE_MST_INF"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_CODE_MST_INF"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_CODE_MST_INF"."CHNR" IS '수정자';
   COMMENT ON COLUMN "APPS"."T_CODE_MST_INF"."CHNG_DTTM" IS '수정일';
   COMMENT ON TABLE "APPS"."T_CODE_MST_INF"  IS '그룹코드';
--------------------------------------------------------
--  DDL for Table T_COMPANY_INF
--------------------------------------------------------

  CREATE TABLE "APPS"."T_COMPANY_INF"
   (	"COMP_SEQ" NUMBER(8,0),
	"COMP_LIC_NUM" VARCHAR2(20 BYTE),
	"COMP_NM" VARCHAR2(200 BYTE),
	"NATION" VARCHAR2(20 BYTE),
	"DEL_YN" CHAR(1 BYTE),
	"REMARKS" VARCHAR2(100 BYTE),
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE DEFAULT SYSDATE,
	"CHNR" NUMBER(8,0),
	"CHNG_DTTM" DATE DEFAULT SYSDATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_COMPANY_INF"."COMP_SEQ" IS '기업SEQ';
   COMMENT ON COLUMN "APPS"."T_COMPANY_INF"."COMP_LIC_NUM" IS '사업자번호';
   COMMENT ON COLUMN "APPS"."T_COMPANY_INF"."COMP_NM" IS '기업명';
   COMMENT ON COLUMN "APPS"."T_COMPANY_INF"."NATION" IS '국가';
   COMMENT ON COLUMN "APPS"."T_COMPANY_INF"."DEL_YN" IS '삭제여부';
   COMMENT ON COLUMN "APPS"."T_COMPANY_INF"."REMARKS" IS '비고';
   COMMENT ON COLUMN "APPS"."T_COMPANY_INF"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_COMPANY_INF"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_COMPANY_INF"."CHNR" IS '수정자';
   COMMENT ON COLUMN "APPS"."T_COMPANY_INF"."CHNG_DTTM" IS '수정일';
   COMMENT ON TABLE "APPS"."T_COMPANY_INF"  IS '기업관리';
--------------------------------------------------------
--  DDL for Table T_FILE_INF
--------------------------------------------------------

  CREATE TABLE "APPS"."T_FILE_INF"
   (	"FILE_ID" VARCHAR2(200 BYTE),
	"REF_CODE" VARCHAR2(50 BYTE),
	"REF_SEQ" NUMBER(38,0),
	"SORT_ORD" NUMBER(8,0),
	"FILE_NAME" VARCHAR2(1000 BYTE),
	"FILE_EXT" VARCHAR2(30 BYTE),
	"FILE_NAME_DEST" VARCHAR2(1000 BYTE),
	"FILE_PATH" VARCHAR2(1000 BYTE),
	"FILE_SIZE" NUMBER(12,0),
	"DEL_YN" CHAR(1 BYTE) DEFAULT 'N',
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE DEFAULT SYSDATE,
	"CHNR" NUMBER(8,0),
	"CHNG_DTTM" DATE DEFAULT SYSDATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_FILE_INF"."FILE_ID" IS '파일 ID';
   COMMENT ON COLUMN "APPS"."T_FILE_INF"."REF_CODE" IS '참조 CD';
   COMMENT ON COLUMN "APPS"."T_FILE_INF"."REF_SEQ" IS '참조 SEQ';
   COMMENT ON COLUMN "APPS"."T_FILE_INF"."SORT_ORD" IS '정렬순서';
   COMMENT ON COLUMN "APPS"."T_FILE_INF"."FILE_NAME" IS '파일명';
   COMMENT ON COLUMN "APPS"."T_FILE_INF"."FILE_EXT" IS '확장자';
   COMMENT ON COLUMN "APPS"."T_FILE_INF"."FILE_NAME_DEST" IS '저장명';
   COMMENT ON COLUMN "APPS"."T_FILE_INF"."FILE_PATH" IS '저장경로';
   COMMENT ON COLUMN "APPS"."T_FILE_INF"."FILE_SIZE" IS '파일크기';
   COMMENT ON COLUMN "APPS"."T_FILE_INF"."DEL_YN" IS '삭제여부';
   COMMENT ON COLUMN "APPS"."T_FILE_INF"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_FILE_INF"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_FILE_INF"."CHNR" IS '수정자';
   COMMENT ON COLUMN "APPS"."T_FILE_INF"."CHNG_DTTM" IS '수정일';
   COMMENT ON TABLE "APPS"."T_FILE_INF"  IS '공통파일';
--------------------------------------------------------
--  DDL for Table T_MEMB_INF
--------------------------------------------------------

  CREATE TABLE "APPS"."T_MEMB_INF"
   (	"MEMB_SEQ" NUMBER(8,0),
	"COMP_SEQ" NUMBER(8,0),
	"EMAIL" VARCHAR2(50 BYTE),
	"PSWD" VARCHAR2(300 BYTE),
	"SALT" VARCHAR2(100 BYTE),
	"MEMB_NAME" VARCHAR2(50 BYTE),
	"DEPARTMENT" VARCHAR2(50 BYTE),
	"AUTH" VARCHAR2(20 BYTE),
	"PHONE" VARCHAR2(50 BYTE),
	"JOIN_DTTM" DATE DEFAULT SYSDATE,
	"STATUS" VARCHAR2(20 BYTE),
	"USE_YN" CHAR(1 BYTE) DEFAULT 'Y',
	"WTDR_YN" CHAR(1 BYTE) DEFAULT 'N',
	"WTDR_DTTM" DATE DEFAULT SYSDATE,
	"PSWD_CHNG_DTTM" DATE DEFAULT SYSDATE,
	"PSWD_ERR_COUNT" NUMBER(8,0),
	"PSWD_INIT_YN" CHAR(1 BYTE) DEFAULT 'N',
	"PSWD_EXP_DTTM" DATE,
	"RCT_ACS_DTTM" DATE,
	"RCT_ACS_IP" VARCHAR2(100 BYTE),
	"DORMANT_YN" CHAR(1 BYTE) DEFAULT 'N',
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE DEFAULT SYSDATE,
	"CHNR" NUMBER(8,0),
	"CHNG_DTTM" DATE DEFAULT SYSDATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."MEMB_SEQ" IS '사용자 SEQ';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."COMP_SEQ" IS '기업SEQ';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."PSWD" IS '비밀번호';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."SALT" IS '암호화키값';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."MEMB_NAME" IS '이름';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."DEPARTMENT" IS '부서';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."AUTH" IS '권한';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."PHONE" IS '연락처';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."JOIN_DTTM" IS '가입일';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."STATUS" IS '가입 상태';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."USE_YN" IS '사용여부';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."WTDR_YN" IS '탈퇴여부';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."WTDR_DTTM" IS '탈퇴일';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."PSWD_CHNG_DTTM" IS '비밀번호 변경일';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."PSWD_ERR_COUNT" IS '비밀번호 틀린 횟수';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."PSWD_INIT_YN" IS '비밀번호 초기화여부';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."PSWD_EXP_DTTM" IS '비밀번호 만료일';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."RCT_ACS_DTTM" IS '최근 접속일';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."RCT_ACS_IP" IS '최근 접속 IP';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."DORMANT_YN" IS '휴면여부';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."CHNR" IS '수정자';
   COMMENT ON COLUMN "APPS"."T_MEMB_INF"."CHNG_DTTM" IS '수정일';
   COMMENT ON TABLE "APPS"."T_MEMB_INF"  IS '사용자관리';
--------------------------------------------------------
--  DDL for Table T_MEMB_TERMS_AGRMNT_H
--------------------------------------------------------

  CREATE TABLE "APPS"."T_MEMB_TERMS_AGRMNT_H"
   (	"MEMB_SEQ" NUMBER(8,0),
	"TERMS_CD" VARCHAR2(30 BYTE),
	"AGREE_YN" CHAR(1 BYTE) DEFAULT 'N',
	"RGT_DTTM" DATE DEFAULT SYSDATE,
	"RGTR" NUMBER(8,0)
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_MEMB_TERMS_AGRMNT_H"."MEMB_SEQ" IS '사용자SEQ';
   COMMENT ON COLUMN "APPS"."T_MEMB_TERMS_AGRMNT_H"."TERMS_CD" IS '약관CD';
   COMMENT ON COLUMN "APPS"."T_MEMB_TERMS_AGRMNT_H"."AGREE_YN" IS '동의여부';
   COMMENT ON COLUMN "APPS"."T_MEMB_TERMS_AGRMNT_H"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_MEMB_TERMS_AGRMNT_H"."RGTR" IS '등록자';
   COMMENT ON TABLE "APPS"."T_MEMB_TERMS_AGRMNT_H"  IS '사용자 약관동의';
--------------------------------------------------------
--  DDL for Table T_MEMB_WTHDR_INF
--------------------------------------------------------

  CREATE TABLE "APPS"."T_MEMB_WTHDR_INF"
   (	"WTHDR_SEQ" NUMBER(8,0),
	"MEMB_SEQ" NUMBER(8,0),
	"WTHDR_RSN" VARCHAR2(30 BYTE),
	"DEL_ACNT" CHAR(1 BYTE),
	"DEL_INTRL" CHAR(1 BYTE),
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE DEFAULT SYSDATE,
	"WTHDR_RSN_TXT" VARCHAR2(500 BYTE)
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_MEMB_WTHDR_INF"."WTHDR_SEQ" IS '탈회SEQ';
   COMMENT ON COLUMN "APPS"."T_MEMB_WTHDR_INF"."MEMB_SEQ" IS '사용자SEQ';
   COMMENT ON COLUMN "APPS"."T_MEMB_WTHDR_INF"."WTHDR_RSN" IS '탈회사유';
   COMMENT ON COLUMN "APPS"."T_MEMB_WTHDR_INF"."DEL_ACNT" IS '계정삭제동의';
   COMMENT ON COLUMN "APPS"."T_MEMB_WTHDR_INF"."DEL_INTRL" IS '연동정보삭제동의';
   COMMENT ON COLUMN "APPS"."T_MEMB_WTHDR_INF"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_MEMB_WTHDR_INF"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_MEMB_WTHDR_INF"."WTHDR_RSN_TXT" IS '탈회사유 기타';
   COMMENT ON TABLE "APPS"."T_MEMB_WTHDR_INF"  IS '탈회 정보';
--------------------------------------------------------
--  DDL for Table T_MID_MST
--------------------------------------------------------

  CREATE TABLE "APPS"."T_MID_MST"
   (	"MID_SEQ" NUMBER(8,0),
	"COMP_SEQ" NUMBER(8,0),
	"MID_NAME" VARCHAR2(200 BYTE),
	"MID_CODE" VARCHAR2(200 BYTE),
	"MERCHANT_KEY" VARCHAR2(200 BYTE),
	"CURRENCY_TYPE" VARCHAR2(20 BYTE),
	"CARD_FEE_RATE" VARCHAR2(20 BYTE),
	"PG_FEE_RATE" VARCHAR2(20 BYTE),
	"NICE_FEE_RATE" VARCHAR2(20 BYTE),
	"FROM_DATE" CHAR(10 BYTE),
	"TO_DATE" CHAR(10 BYTE),
	"USE_YN" CHAR(1 BYTE) DEFAULT 'Y',
	"DEL_YN" CHAR(1 BYTE) DEFAULT 'N',
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE,
	"CHNR" NUMBER(8,0),
	"CHNG_DTTM" DATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_MID_MST"."MID_SEQ" IS 'MID SEQ';
   COMMENT ON COLUMN "APPS"."T_MID_MST"."COMP_SEQ" IS '기업SEQ';
   COMMENT ON COLUMN "APPS"."T_MID_MST"."MID_NAME" IS 'MID 명칭';
   COMMENT ON COLUMN "APPS"."T_MID_MST"."MID_CODE" IS 'MID 코드';
   COMMENT ON COLUMN "APPS"."T_MID_MST"."MERCHANT_KEY" IS 'MERCHANT KEY';
   COMMENT ON COLUMN "APPS"."T_MID_MST"."CURRENCY_TYPE" IS '통화타입';
   COMMENT ON COLUMN "APPS"."T_MID_MST"."CARD_FEE_RATE" IS '카드사수수료율';
   COMMENT ON COLUMN "APPS"."T_MID_MST"."PG_FEE_RATE" IS 'PG사 수수료율';
   COMMENT ON COLUMN "APPS"."T_MID_MST"."NICE_FEE_RATE" IS '운영사 수수료율';
   COMMENT ON COLUMN "APPS"."T_MID_MST"."FROM_DATE" IS '적용시작날짜';
   COMMENT ON COLUMN "APPS"."T_MID_MST"."TO_DATE" IS '적용종료날짜';
   COMMENT ON COLUMN "APPS"."T_MID_MST"."USE_YN" IS '사용여부';
   COMMENT ON COLUMN "APPS"."T_MID_MST"."DEL_YN" IS '삭제여부';
   COMMENT ON COLUMN "APPS"."T_MID_MST"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_MID_MST"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_MID_MST"."CHNR" IS '수정자';
   COMMENT ON COLUMN "APPS"."T_MID_MST"."CHNG_DTTM" IS '수정일';
   COMMENT ON TABLE "APPS"."T_MID_MST"  IS 'MID 관리';
--------------------------------------------------------
--  DDL for Table T_MLTLN_MST
--------------------------------------------------------

  CREATE TABLE "APPS"."T_MLTLN_MST"
   (	"CODE" VARCHAR2(500 BYTE),
	"CODE_NM_KO" VARCHAR2(1000 BYTE),
	"CODE_NM_EN" VARCHAR2(1000 BYTE),
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_MLTLN_MST"."CODE" IS '코드';
   COMMENT ON COLUMN "APPS"."T_MLTLN_MST"."CODE_NM_KO" IS '한국어';
   COMMENT ON COLUMN "APPS"."T_MLTLN_MST"."CODE_NM_EN" IS '영어';
   COMMENT ON COLUMN "APPS"."T_MLTLN_MST"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_MLTLN_MST"."RGT_DTTM" IS '등록일';
   COMMENT ON TABLE "APPS"."T_MLTLN_MST"  IS '다국어 마스터';
--------------------------------------------------------
--  DDL for Table T_POPUP_INF
--------------------------------------------------------

  CREATE TABLE "APPS"."T_POPUP_INF"
   (	"POPUP_SEQ" NUMBER(8,0),
	"POPUP_MST_CD" VARCHAR2(30 BYTE),
	"POPUP_NAME" VARCHAR2(200 BYTE),
	"FROM_DATE" CHAR(10 BYTE),
	"TO_DATE" CHAR(10 BYTE),
	"POPUP_DESC" VARCHAR2(500 BYTE),
	"CLOSE_OPT" CHAR(1 BYTE) DEFAULT '1',
	"POPUP_URL" VARCHAR2(100 BYTE),
	"POPUP_WIDTH" NUMBER(8,0),
	"POPUP_HEIGHT" NUMBER(8,0),
	"CLICKS" NUMBER(8,0),
	"SORT_ORD" NUMBER(8,0),
	"USE_YN" CHAR(1 BYTE) DEFAULT 'Y',
	"DEL_YN" CHAR(1 BYTE) DEFAULT 'N',
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE DEFAULT SYSDATE,
	"CHNR" NUMBER(8,0),
	"CHNG_DTTM" DATE DEFAULT SYSDATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_POPUP_INF"."POPUP_SEQ" IS '팝업SEQ';
   COMMENT ON COLUMN "APPS"."T_POPUP_INF"."POPUP_MST_CD" IS '팝업마스터CD';
   COMMENT ON COLUMN "APPS"."T_POPUP_INF"."POPUP_NAME" IS '배너명';
   COMMENT ON COLUMN "APPS"."T_POPUP_INF"."FROM_DATE" IS '시작일. 팝업게시 시작일';
   COMMENT ON COLUMN "APPS"."T_POPUP_INF"."TO_DATE" IS '종료일. 팝업게시 종료일';
   COMMENT ON COLUMN "APPS"."T_POPUP_INF"."POPUP_DESC" IS '팝업설명';
   COMMENT ON COLUMN "APPS"."T_POPUP_INF"."CLOSE_OPT" IS '닫기옵션. 1:당일안보기';
   COMMENT ON COLUMN "APPS"."T_POPUP_INF"."POPUP_URL" IS '팝업이동URL';
   COMMENT ON COLUMN "APPS"."T_POPUP_INF"."POPUP_WIDTH" IS '가로길이';
   COMMENT ON COLUMN "APPS"."T_POPUP_INF"."POPUP_HEIGHT" IS '새로길이';
   COMMENT ON COLUMN "APPS"."T_POPUP_INF"."CLICKS" IS '클릭횟수';
   COMMENT ON COLUMN "APPS"."T_POPUP_INF"."SORT_ORD" IS '정렬순서';
   COMMENT ON COLUMN "APPS"."T_POPUP_INF"."USE_YN" IS '사용여부';
   COMMENT ON COLUMN "APPS"."T_POPUP_INF"."DEL_YN" IS '삭제여부';
   COMMENT ON COLUMN "APPS"."T_POPUP_INF"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_POPUP_INF"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_POPUP_INF"."CHNR" IS '수정자';
   COMMENT ON COLUMN "APPS"."T_POPUP_INF"."CHNG_DTTM" IS '수정일';
   COMMENT ON TABLE "APPS"."T_POPUP_INF"  IS '팝업';
--------------------------------------------------------
--  DDL for Table T_POPUP_MST_INF
--------------------------------------------------------

  CREATE TABLE "APPS"."T_POPUP_MST_INF"
   (	"POPUP_MST_CD" VARCHAR2(30 BYTE),
	"POPUP_TYPE" VARCHAR2(30 BYTE),
	"POPUP_MST_NAME" VARCHAR2(30 BYTE),
	"POPUP_MST_DESC" VARCHAR2(200 BYTE),
	"USE_YN" CHAR(1 BYTE) DEFAULT 'Y',
	"WIDTH" NUMBER(8,0),
	"HEIGHT" NUMBER(8,0),
	"PREVIEW_URL" VARCHAR2(500 BYTE),
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE DEFAULT SYSDATE,
	"CHNR" NUMBER(8,0),
	"CHNG_DTTM" DATE DEFAULT SYSDATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_POPUP_MST_INF"."POPUP_MST_CD" IS '팝업마스터CD';
   COMMENT ON COLUMN "APPS"."T_POPUP_MST_INF"."POPUP_TYPE" IS '팝업 종류. 앱/웹 구분';
   COMMENT ON COLUMN "APPS"."T_POPUP_MST_INF"."POPUP_MST_NAME" IS '팝업마스터명';
   COMMENT ON COLUMN "APPS"."T_POPUP_MST_INF"."POPUP_MST_DESC" IS '팝업마스터설명';
   COMMENT ON COLUMN "APPS"."T_POPUP_MST_INF"."USE_YN" IS '사용여부';
   COMMENT ON COLUMN "APPS"."T_POPUP_MST_INF"."WIDTH" IS '가로길이';
   COMMENT ON COLUMN "APPS"."T_POPUP_MST_INF"."HEIGHT" IS '세로길이';
   COMMENT ON COLUMN "APPS"."T_POPUP_MST_INF"."PREVIEW_URL" IS '미리보기URL';
   COMMENT ON COLUMN "APPS"."T_POPUP_MST_INF"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_POPUP_MST_INF"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_POPUP_MST_INF"."CHNR" IS '수정자';
   COMMENT ON COLUMN "APPS"."T_POPUP_MST_INF"."CHNG_DTTM" IS '수정일';
   COMMENT ON TABLE "APPS"."T_POPUP_MST_INF"  IS '팝업마스터';
--------------------------------------------------------
--  DDL for Table T_SHORT_URL_INF
--------------------------------------------------------

  CREATE TABLE "APPS"."T_SHORT_URL_INF"
   (	"URL_ID" VARCHAR2(200 BYTE),
	"URL" VARCHAR2(4000 BYTE),
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE DEFAULT SYSDATE,
	"HITS" NUMBER(8,0),
	"LAST_DTTM" DATE DEFAULT SYSDATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_SHORT_URL_INF"."URL_ID" IS 'URL ID';
   COMMENT ON COLUMN "APPS"."T_SHORT_URL_INF"."URL" IS 'URL';
   COMMENT ON COLUMN "APPS"."T_SHORT_URL_INF"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_SHORT_URL_INF"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_SHORT_URL_INF"."HITS" IS '접근 클릭수';
   COMMENT ON COLUMN "APPS"."T_SHORT_URL_INF"."LAST_DTTM" IS '최근사용일';
   COMMENT ON TABLE "APPS"."T_SHORT_URL_INF"  IS '단축 URL 정보';
--------------------------------------------------------
--  DDL for Table T_SYS_PROP_INF
--------------------------------------------------------

  CREATE TABLE "APPS"."T_SYS_PROP_INF"
   (	"SYS_KEY" VARCHAR2(500 BYTE),
	"SYS_VALUE" VARCHAR2(1000 BYTE),
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE DEFAULT SYSDATE,
	"CHNR" NUMBER(8,0),
	"CHNG_DTTM" DATE DEFAULT SYSDATE
   ) TABLESPACE "TSD_APPS_DEFT" ;

   COMMENT ON COLUMN "APPS"."T_SYS_PROP_INF"."SYS_KEY" IS '시스템프로퍼티 KEY';
   COMMENT ON COLUMN "APPS"."T_SYS_PROP_INF"."SYS_VALUE" IS '시스템프로퍼티 값';
   COMMENT ON COLUMN "APPS"."T_SYS_PROP_INF"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_SYS_PROP_INF"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_SYS_PROP_INF"."CHNR" IS '수정자';
   COMMENT ON COLUMN "APPS"."T_SYS_PROP_INF"."CHNG_DTTM" IS '수정일';
   COMMENT ON TABLE "APPS"."T_SYS_PROP_INF"  IS '시스템프로퍼티';
--------------------------------------------------------
--  DDL for Table T_TERMS_INF
--------------------------------------------------------

  CREATE TABLE "APPS"."T_TERMS_INF"
   (	"TERMS_CD" VARCHAR2(30 BYTE),
	"VERSION" VARCHAR2(30 BYTE),
	"TERMS_TYPE" VARCHAR2(30 BYTE),
	"CONTENT" CLOB,
	"USE_YN" CHAR(1 BYTE) DEFAULT 'Y',
	"REQUIRED_YN" CHAR(1 BYTE) DEFAULT 'Y',
	"FROM_DATE" CHAR(10 BYTE),
	"TO_DATE" CHAR(10 BYTE),
	"REMARKS" VARCHAR2(200 BYTE),
	"RGTR" NUMBER(8,0),
	"RGT_DTTM" DATE DEFAULT SYSDATE,
	"CHNR" NUMBER(8,0),
	"CHNG_DTTM" DATE DEFAULT SYSDATE
   ) TABLESPACE "TSD_APPS_DEFT"
 LOB ("CONTENT") STORE AS SECUREFILE (
  TABLESPACE "TSD_APPS_DEFT" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "APPS"."T_TERMS_INF"."TERMS_CD" IS '약관 CD';
   COMMENT ON COLUMN "APPS"."T_TERMS_INF"."VERSION" IS '버전';
   COMMENT ON COLUMN "APPS"."T_TERMS_INF"."TERMS_TYPE" IS '약관구분. 약관/규정';
   COMMENT ON COLUMN "APPS"."T_TERMS_INF"."CONTENT" IS '내용';
   COMMENT ON COLUMN "APPS"."T_TERMS_INF"."USE_YN" IS '사용여부';
   COMMENT ON COLUMN "APPS"."T_TERMS_INF"."REQUIRED_YN" IS '필수여부';
   COMMENT ON COLUMN "APPS"."T_TERMS_INF"."FROM_DATE" IS '게시시작일';
   COMMENT ON COLUMN "APPS"."T_TERMS_INF"."TO_DATE" IS '게시종료일';
   COMMENT ON COLUMN "APPS"."T_TERMS_INF"."REMARKS" IS '개정메모';
   COMMENT ON COLUMN "APPS"."T_TERMS_INF"."RGTR" IS '등록자';
   COMMENT ON COLUMN "APPS"."T_TERMS_INF"."RGT_DTTM" IS '등록일';
   COMMENT ON COLUMN "APPS"."T_TERMS_INF"."CHNR" IS '수정자';
   COMMENT ON COLUMN "APPS"."T_TERMS_INF"."CHNG_DTTM" IS '수정일';
   COMMENT ON TABLE "APPS"."T_TERMS_INF"  IS '약관';
--------------------------------------------------------
--  DDL for Index IX_t_memb_admin_inf_U01
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_t_memb_admin_inf_U01" ON "APPS"."t_memb_admin_inf" ("A_MEMB_ID")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_t_memb_admin_inf_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_t_memb_admin_inf_P" ON "APPS"."t_memb_admin_inf" ("A_MEMB_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_TOKEN_ACCESS_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_TOKEN_ACCESS_P" ON "APPS"."T_TOKEN_ACCESS" ("TOKEN")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T__TOKEN_BLACKLIST_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T__TOKEN_BLACKLIST_P" ON "APPS"."T__TOKEN_BLACKLIST" ("TOKEN")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_TOKEN_REFRESH_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_TOKEN_REFRESH_P" ON "APPS"."T_TOKEN_REFRESH" ("TOKEN")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_ACCOUNT_INF_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_ACCOUNT_INF_P" ON "APPS"."T_ACCOUNT_INF" ("ACCOUNT_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_BANNER_INF_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_BANNER_INF_P" ON "APPS"."T_BANNER_INF" ("BANNER_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_BANNER_MST_INF_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_BANNER_MST_INF_P" ON "APPS"."T_BANNER_MST_INF" ("BANNER_MST_CD")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_BIN_MST_N01
--------------------------------------------------------

  CREATE INDEX "APPS"."IX_T_BIN_MST_N01" ON "APPS"."T_BIN_MST" ("COMP_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_BIN_MST_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_BIN_MST_P" ON "APPS"."T_BIN_MST" ("BIN_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_BOARD_CMT_INF_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_BOARD_CMT_INF_P" ON "APPS"."T_BOARD_CMT_INF" ("BOARD_CMT_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_BOARD_INF_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_BOARD_INF_P" ON "APPS"."T_BOARD_INF" ("BOARD_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_BOARD_MST_INF_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_BOARD_MST_INF_P" ON "APPS"."T_BOARD_MST_INF" ("BOARD_MST_ID")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_BOARD_OPT_INF_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_BOARD_OPT_INF_P" ON "APPS"."T_BOARD_OPT_INF" ("BOARD_MST_ID")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_CNTRC_INF_N01
--------------------------------------------------------

  CREATE INDEX "APPS"."IX_T_CNTRC_INF_N01" ON "APPS"."T_CNTRC_INF" ("CNTRC_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_CNTRC_INF_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_CNTRC_INF_P" ON "APPS"."T_CNTRC_INF" ("DETAIL_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_CNTRC_LOG_N01
--------------------------------------------------------

  CREATE INDEX "APPS"."IX_T_CNTRC_LOG_N01" ON "APPS"."T_CNTRC_LOG" ("CNTRC_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_CNTRC_LOG_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_CNTRC_LOG_P" ON "APPS"."T_CNTRC_LOG" ("LOG_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_CNTRC_MST_N01
--------------------------------------------------------

  CREATE INDEX "APPS"."IX_T_CNTRC_MST_N01" ON "APPS"."T_CNTRC_MST" ("CNTRC_STATUS")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_CNTRC_MST_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_CNTRC_MST_P" ON "APPS"."T_CNTRC_MST" ("CNTRC_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_CNTRC_PAYMENT_N01
--------------------------------------------------------

  CREATE INDEX "APPS"."IX_T_CNTRC_PAYMENT_N01" ON "APPS"."T_CNTRC_PAYMENT" ("CNTRC_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_CNTRC_PAYMENT_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_CNTRC_PAYMENT_P" ON "APPS"."T_CNTRC_PAYMENT" ("PAYMENT_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_CNTRC_PAYMENT_CANCEL_N01
--------------------------------------------------------

  CREATE INDEX "APPS"."IX_T_CNTRC_PAYMENT_CANCEL_N01" ON "APPS"."T_CNTRC_PAYMENT_CANCEL" ("CNTRC_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_CNTRC_PAYMENT_CANCEL_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_CNTRC_PAYMENT_CANCEL_P" ON "APPS"."T_CNTRC_PAYMENT_CANCEL" ("PAY_CANCEL_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_CNTRC_SETTLE_N01
--------------------------------------------------------

  CREATE INDEX "APPS"."IX_T_CNTRC_SETTLE_N01" ON "APPS"."T_CNTRC_SETTLE" ("CNTRC_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_CNTRC_SETTLE_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_CNTRC_SETTLE_P" ON "APPS"."T_CNTRC_SETTLE" ("SETTLE_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_CNTRC_SIGN_LOG_N01
--------------------------------------------------------

  CREATE INDEX "APPS"."IX_T_CNTRC_SIGN_LOG_N01" ON "APPS"."T_CNTRC_SIGN_LOG" ("CNTRC_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_CNTRC_SIGN_LOG_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_CNTRC_SIGN_LOG_P" ON "APPS"."T_CNTRC_SIGN_LOG" ("SIGN_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_CODE_INF_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_CODE_INF_P" ON "APPS"."T_CODE_INF" ("CODE", "GRP_CODE")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_CODE_MST_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_CODE_MST_P" ON "APPS"."T_CODE_MST_INF" ("GRP_CODE")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_COMPANY_INF_U01
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_COMPANY_INF_U01" ON "APPS"."T_COMPANY_INF" ("COMP_LIC_NUM")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_COMPANY_INF_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_COMPANY_INF_P" ON "APPS"."T_COMPANY_INF" ("COMP_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_FILE_INF_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_FILE_INF_P" ON "APPS"."T_FILE_INF" ("FILE_ID")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_MEMB_INF_N01
--------------------------------------------------------

  CREATE INDEX "APPS"."IX_T_MEMB_INF_N01" ON "APPS"."T_MEMB_INF" ("COMP_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_MEMB_INF_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_MEMB_INF_P" ON "APPS"."T_MEMB_INF" ("MEMB_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_MEMB_WTHDR_INF_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_MEMB_WTHDR_INF_P" ON "APPS"."T_MEMB_WTHDR_INF" ("WTHDR_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_MID_MST_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_MID_MST_P" ON "APPS"."T_MID_MST" ("MID_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_MID_MST_N01
--------------------------------------------------------

  CREATE INDEX "APPS"."IX_T_MID_MST_N01" ON "APPS"."T_MID_MST" ("COMP_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_MLTLN_MST_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_MLTLN_MST_P" ON "APPS"."T_MLTLN_MST" ("CODE")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_POPUP_INF_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_POPUP_INF_P" ON "APPS"."T_POPUP_INF" ("POPUP_SEQ")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_POPUP_MST_INF_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_POPUP_MST_INF_P" ON "APPS"."T_POPUP_MST_INF" ("POPUP_MST_CD")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_SHORT_URL_INF_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_SHORT_URL_INF_P" ON "APPS"."T_SHORT_URL_INF" ("URL_ID")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_SYS_PROP_INF_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_SYS_PROP_INF_P" ON "APPS"."T_SYS_PROP_INF" ("SYS_KEY")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_TERMS_INF_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."IX_T_TERMS_INF_P" ON "APPS"."T_TERMS_INF" ("TERMS_CD", "VERSION")
  TABLESPACE "TSD_APPS_DEFT" ;
--------------------------------------------------------
--  DDL for Index IX_T_MEMB_INF_U01
--------------------------------------------------------

CREATE UNIQUE INDEX "APPS"."IX_T_MEMB_INF_U01" ON "APPS"."T_MEMB_INF" ("EMAIL")
    TABLESPACE "TSD_APPS_DEFT" ;

--------------------------------------------------------
--  Constraints for Table t_memb_admin_inf
--------------------------------------------------------

  ALTER TABLE "APPS"."t_memb_admin_inf" MODIFY ("A_MEMB_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."t_memb_admin_inf" MODIFY ("A_MEMB_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."t_memb_admin_inf" MODIFY ("AUTH_TYPE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."t_memb_admin_inf" MODIFY ("A_MEMB_PSWD" NOT NULL ENABLE);
  ALTER TABLE "APPS"."t_memb_admin_inf" MODIFY ("A_MEMB_SALT" NOT NULL ENABLE);
  ALTER TABLE "APPS"."t_memb_admin_inf" MODIFY ("A_MEMB_NAME" NOT NULL ENABLE);
  ALTER TABLE "APPS"."t_memb_admin_inf" MODIFY ("A_PSWD_CHNG_DTTM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."t_memb_admin_inf" MODIFY ("A_PSWD_ERR_COUNT" NOT NULL ENABLE);
  ALTER TABLE "APPS"."t_memb_admin_inf" MODIFY ("A_PSWD_INIT_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."t_memb_admin_inf" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."t_memb_admin_inf" ADD CONSTRAINT "IX_T_MEMB_ADMIN_INF_P" PRIMARY KEY ("A_MEMB_SEQ")
  USING INDEX (CREATE UNIQUE INDEX "APPS"."IX_t_memb_admin_inf_P" ON "APPS"."t_memb_admin_inf" ("A_MEMB_SEQ")
  TABLESPACE "TSD_APPS_DEFT" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table T__MEMB_LOG_H
--------------------------------------------------------

  ALTER TABLE "APPS"."T__MEMB_LOG_H" MODIFY ("LOG_DATE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T__MEMB_LOG_H" MODIFY ("MEMB_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T__MEMB_LOG_H" MODIFY ("LOG_TYPE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T__MEMB_LOG_H" MODIFY ("SITE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T__MEMB_LOG_H" MODIFY ("LOG_JSON" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_TOKEN_ACCESS
--------------------------------------------------------

  ALTER TABLE "APPS"."T_TOKEN_ACCESS" MODIFY ("TOKEN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_TOKEN_ACCESS" MODIFY ("SITE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_TOKEN_ACCESS" MODIFY ("EXP_DATE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_TOKEN_ACCESS" MODIFY ("RGT_DTTM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_TOKEN_ACCESS" ADD CONSTRAINT "IX_T_TOKEN_ACCESS_P" PRIMARY KEY ("TOKEN")
  USING INDEX (CREATE UNIQUE INDEX "APPS"."IX_T_TOKEN_ACCESS_P" ON "APPS"."T_TOKEN_ACCESS" ("TOKEN")
  TABLESPACE "TSD_APPS_DEFT" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table T__TOKEN_BLACKLIST
--------------------------------------------------------

  ALTER TABLE "APPS"."T__TOKEN_BLACKLIST" MODIFY ("TOKEN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T__TOKEN_BLACKLIST" MODIFY ("SITE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T__TOKEN_BLACKLIST" MODIFY ("EXP_DATE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T__TOKEN_BLACKLIST" MODIFY ("RGT_DTTM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T__TOKEN_BLACKLIST" ADD CONSTRAINT "IX_T_TOKEN_BLACKLIST_P" PRIMARY KEY ("TOKEN")
  USING INDEX (CREATE UNIQUE INDEX "APPS"."IX_T__TOKEN_BLACKLIST_P" ON "APPS"."T__TOKEN_BLACKLIST" ("TOKEN")
  TABLESPACE "TSD_APPS_DEFT" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_TOKEN_REFRESH
--------------------------------------------------------

  ALTER TABLE "APPS"."T_TOKEN_REFRESH" MODIFY ("TOKEN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_TOKEN_REFRESH" MODIFY ("SITE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_TOKEN_REFRESH" MODIFY ("EXP_DATE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_TOKEN_REFRESH" MODIFY ("RGT_DTTM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_TOKEN_REFRESH" ADD CONSTRAINT "IX_T_TOKEN_REFRESH_P" PRIMARY KEY ("TOKEN")
  USING INDEX (CREATE UNIQUE INDEX "APPS"."IX_T_TOKEN_REFRESH_P" ON "APPS"."T_TOKEN_REFRESH" ("TOKEN")
  TABLESPACE "TSD_APPS_DEFT" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_ACCOUNT_INF
--------------------------------------------------------

  ALTER TABLE "APPS"."T_ACCOUNT_INF" MODIFY ("ACCOUNT_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_ACCOUNT_INF" MODIFY ("COMP_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_ACCOUNT_INF" MODIFY ("BANK_CODE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_ACCOUNT_INF" MODIFY ("ACCOUNT_NUM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_ACCOUNT_INF" MODIFY ("CURRENCY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_ACCOUNT_INF" MODIFY ("ACCOUNT_HOLDER" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_ACCOUNT_INF" MODIFY ("RGTR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_ACCOUNT_INF" MODIFY ("RGT_DTTM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_ACCOUNT_INF" ADD CONSTRAINT "IX_T_ACCOUNT_INF_P" PRIMARY KEY ("ACCOUNT_SEQ")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_API_PROC_H
--------------------------------------------------------

  ALTER TABLE "APPS"."T_API_PROC_H" MODIFY ("API_LOG_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_API_PROC_H" MODIFY ("MEMB_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_API_PROC_H" MODIFY ("RGT_DTTM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_BANNER_INF
--------------------------------------------------------

  ALTER TABLE "APPS"."T_BANNER_INF" MODIFY ("BANNER_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BANNER_INF" MODIFY ("BANNER_MST_CD" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BANNER_INF" MODIFY ("BANNER_NAME" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BANNER_INF" MODIFY ("CLICKS" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BANNER_INF" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BANNER_INF" MODIFY ("DEL_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BANNER_INF" MODIFY ("RGTR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BANNER_INF" ADD CONSTRAINT "IX_T_BANNER_INF_P" PRIMARY KEY ("BANNER_SEQ")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_BANNER_MST_INF
--------------------------------------------------------

  ALTER TABLE "APPS"."T_BANNER_MST_INF" MODIFY ("BANNER_MST_CD" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BANNER_MST_INF" MODIFY ("BANNER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BANNER_MST_INF" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BANNER_MST_INF" MODIFY ("RGTR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BANNER_MST_INF" ADD CONSTRAINT "IX_T_BANNER_MST_INF_P" PRIMARY KEY ("BANNER_MST_CD")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_BIN_MST
--------------------------------------------------------

  ALTER TABLE "APPS"."T_BIN_MST" MODIFY ("BIN_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BIN_MST" MODIFY ("COMP_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BIN_MST" MODIFY ("BIN_NAME" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BIN_MST" MODIFY ("START_SCTN1" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BIN_MST" MODIFY ("START_SCTN2" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BIN_MST" MODIFY ("START_SCTN3" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BIN_MST" MODIFY ("START_SCTN4" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BIN_MST" MODIFY ("END_SCTN1" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BIN_MST" MODIFY ("END_SCTN2" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BIN_MST" MODIFY ("END_SCTN3" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BIN_MST" MODIFY ("END_SCTN4" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BIN_MST" MODIFY ("FROM_DATE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BIN_MST" MODIFY ("TO_DATE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BIN_MST" MODIFY ("RGTR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BIN_MST" MODIFY ("RGT_DTTM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BIN_MST" ADD CONSTRAINT "IX_T_BIN_MST_P" PRIMARY KEY ("BIN_SEQ")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_BOARD_CMT_INF
--------------------------------------------------------

  ALTER TABLE "APPS"."T_BOARD_CMT_INF" MODIFY ("BOARD_CMT_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_CMT_INF" MODIFY ("BOARD_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_CMT_INF" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_CMT_INF" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_CMT_INF" MODIFY ("DEL_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_CMT_INF" MODIFY ("ADMIN_DEL_CD" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_CMT_INF" MODIFY ("ORG_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_CMT_INF" MODIFY ("SORT_ORD" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_CMT_INF" MODIFY ("RGTR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_CMT_INF" ADD CONSTRAINT "IX_T_BOARD_CMT_INF_P" PRIMARY KEY ("BOARD_CMT_SEQ")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_BOARD_INF
--------------------------------------------------------

  ALTER TABLE "APPS"."T_BOARD_INF" MODIFY ("BOARD_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_INF" MODIFY ("BOARD_MST_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_INF" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_INF" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_INF" MODIFY ("ORG_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_INF" MODIFY ("SORT_ORD" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_INF" MODIFY ("DEL_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_INF" MODIFY ("RGTR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_INF" ADD CONSTRAINT "IX_T_BOARD_INF_P" PRIMARY KEY ("BOARD_SEQ")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_BOARD_MST_INF
--------------------------------------------------------

  ALTER TABLE "APPS"."T_BOARD_MST_INF" MODIFY ("BOARD_MST_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_MST_INF" MODIFY ("BOARD_NAME" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_MST_INF" MODIFY ("BOARD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_MST_INF" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_MST_INF" MODIFY ("RGTR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_MST_INF" ADD CONSTRAINT "IX_T_BOARD_MST_INF_P" PRIMARY KEY ("BOARD_MST_ID")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_BOARD_OPT_INF
--------------------------------------------------------

  ALTER TABLE "APPS"."T_BOARD_OPT_INF" MODIFY ("BOARD_MST_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_BOARD_OPT_INF" ADD CONSTRAINT "IX_T_BOARD_OPT_INF_P" PRIMARY KEY ("BOARD_MST_ID")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_CNTRC_INF
--------------------------------------------------------

  ALTER TABLE "APPS"."T_CNTRC_INF" MODIFY ("DETAIL_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_INF" MODIFY ("CNTRC_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_INF" ADD CONSTRAINT "IX_T_CNTRC_INF_P" PRIMARY KEY ("DETAIL_SEQ")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_CNTRC_LOG
--------------------------------------------------------

  ALTER TABLE "APPS"."T_CNTRC_LOG" MODIFY ("LOG_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_LOG" MODIFY ("CNTRC_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_LOG" ADD CONSTRAINT "IX_T_CNTRC_LOG_P" PRIMARY KEY ("LOG_SEQ")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_CNTRC_MST
--------------------------------------------------------

  ALTER TABLE "APPS"."T_CNTRC_MST" MODIFY ("CNTRC_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_MST" MODIFY ("CNTRC_STATUS" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_MST" MODIFY ("RGTR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_MST" MODIFY ("RGT_DTTM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_MST" ADD CONSTRAINT "IX_T_CNTRC_MST_P" PRIMARY KEY ("CNTRC_SEQ")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_CNTRC_PAYMENT
--------------------------------------------------------

  ALTER TABLE "APPS"."T_CNTRC_PAYMENT" MODIFY ("PAYMENT_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT" MODIFY ("CNTRC_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT" MODIFY ("MID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT" MODIFY ("TID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT" MODIFY ("MOID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT" MODIFY ("AUTH_CODE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT" MODIFY ("AUTH_DATE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT" MODIFY ("ACQU_CARD_CODE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT" MODIFY ("ACQU_CARD_NAME" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT" MODIFY ("CARD_NO" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT" MODIFY ("CARD_CODE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT" MODIFY ("CARD_NAME" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT" MODIFY ("CARD_QUOTA" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT" MODIFY ("RGTR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT" MODIFY ("RGT_DTTM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT" ADD CONSTRAINT "IX_T_CNTRC_PAYMENT_P" PRIMARY KEY ("PAYMENT_SEQ")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_CNTRC_PAYMENT_CANCEL
--------------------------------------------------------

  ALTER TABLE "APPS"."T_CNTRC_PAYMENT_CANCEL" MODIFY ("PAY_CANCEL_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT_CANCEL" MODIFY ("CNTRC_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT_CANCEL" MODIFY ("CANCEL_AMT" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT_CANCEL" MODIFY ("MID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT_CANCEL" MODIFY ("MOID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT_CANCEL" MODIFY ("PAY_METHOD" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT_CANCEL" MODIFY ("TID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT_CANCEL" MODIFY ("CANCEL_NUM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT_CANCEL" MODIFY ("CANCEL_DATE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT_CANCEL" MODIFY ("CANCEL_TIME" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT_CANCEL" MODIFY ("RGT_DTTM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_PAYMENT_CANCEL" ADD CONSTRAINT "IX_T_CNTRC_PAYMENT_CANCEL_P" PRIMARY KEY ("PAY_CANCEL_SEQ")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_CNTRC_SETTLE
--------------------------------------------------------

  ALTER TABLE "APPS"."T_CNTRC_SETTLE" MODIFY ("SETTLE_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_SETTLE" MODIFY ("CNTRC_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_SETTLE" MODIFY ("SETTLE_STATUS" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_SETTLE" MODIFY ("MID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_SETTLE" MODIFY ("SUB_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_SETTLE" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_SETTLE" MODIFY ("REQ_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_SETTLE" MODIFY ("DUP_CHK_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_SETTLE" MODIFY ("SETTLE_DT" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_SETTLE" MODIFY ("RGT_DTTM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_SETTLE" ADD CONSTRAINT "IX_T_CNTRC_SETTLE_P" PRIMARY KEY ("SETTLE_SEQ")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_CNTRC_SIGN_LOG
--------------------------------------------------------

  ALTER TABLE "APPS"."T_CNTRC_SIGN_LOG" MODIFY ("SIGN_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_SIGN_LOG" MODIFY ("CNTRC_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_SIGN_LOG" MODIFY ("COMPANY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_SIGN_LOG" MODIFY ("FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_SIGN_LOG" MODIFY ("RGTR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_SIGN_LOG" MODIFY ("RGT_DTTM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CNTRC_SIGN_LOG" ADD CONSTRAINT "IX_T_CNTRC_SIGN_LOG_P" PRIMARY KEY ("SIGN_SEQ")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_CODE_INF
--------------------------------------------------------

  ALTER TABLE "APPS"."T_CODE_INF" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CODE_INF" MODIFY ("GRP_CODE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CODE_INF" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CODE_INF" MODIFY ("RGTR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CODE_INF" ADD CONSTRAINT "IX_T_CODE_INF_P" PRIMARY KEY ("CODE", "GRP_CODE")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_CODE_MST_INF
--------------------------------------------------------

  ALTER TABLE "APPS"."T_CODE_MST_INF" MODIFY ("GRP_CODE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CODE_MST_INF" MODIFY ("GRP_CODE_NAME" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CODE_MST_INF" MODIFY ("RGTR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_CODE_MST_INF" ADD CONSTRAINT "IX_T_CODE_MST_P" PRIMARY KEY ("GRP_CODE")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_COMPANY_INF
--------------------------------------------------------

  ALTER TABLE "APPS"."T_COMPANY_INF" MODIFY ("COMP_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_COMPANY_INF" MODIFY ("COMP_LIC_NUM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_COMPANY_INF" MODIFY ("COMP_NM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_COMPANY_INF" MODIFY ("NATION" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_COMPANY_INF" MODIFY ("DEL_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_COMPANY_INF" MODIFY ("RGTR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_COMPANY_INF" MODIFY ("RGT_DTTM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_COMPANY_INF" ADD CONSTRAINT "IX_T_COMPANY_INF_P" PRIMARY KEY ("COMP_SEQ")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_FILE_INF
--------------------------------------------------------

  ALTER TABLE "APPS"."T_FILE_INF" MODIFY ("FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_FILE_INF" MODIFY ("REF_CODE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_FILE_INF" MODIFY ("REF_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_FILE_INF" MODIFY ("FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_FILE_INF" MODIFY ("FILE_NAME_DEST" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_FILE_INF" MODIFY ("FILE_PATH" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_FILE_INF" MODIFY ("FILE_SIZE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_FILE_INF" MODIFY ("DEL_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_FILE_INF" MODIFY ("RGTR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_FILE_INF" MODIFY ("RGT_DTTM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_FILE_INF" ADD CONSTRAINT "IX_T_FILE_INF_P" PRIMARY KEY ("FILE_ID")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_MEMB_INF
--------------------------------------------------------

  ALTER TABLE "APPS"."T_MEMB_INF" MODIFY ("MEMB_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_INF" MODIFY ("COMP_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_INF" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_INF" MODIFY ("PSWD" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_INF" MODIFY ("MEMB_NAME" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_INF" MODIFY ("AUTH" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_INF" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_INF" MODIFY ("JOIN_DTTM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_INF" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_INF" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_INF" MODIFY ("WTDR_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_INF" MODIFY ("PSWD_CHNG_DTTM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_INF" MODIFY ("PSWD_ERR_COUNT" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_INF" MODIFY ("PSWD_INIT_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_INF" MODIFY ("DORMANT_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_INF" MODIFY ("RGTR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_INF" MODIFY ("RGT_DTTM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_INF" ADD CONSTRAINT "IX_T_MEMB_INF_P" PRIMARY KEY ("MEMB_SEQ")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_MEMB_TERMS_AGRMNT_H
--------------------------------------------------------

  ALTER TABLE "APPS"."T_MEMB_TERMS_AGRMNT_H" MODIFY ("MEMB_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_TERMS_AGRMNT_H" MODIFY ("TERMS_CD" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_TERMS_AGRMNT_H" MODIFY ("AGREE_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_TERMS_AGRMNT_H" MODIFY ("RGT_DTTM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_TERMS_AGRMNT_H" MODIFY ("RGTR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_MEMB_WTHDR_INF
--------------------------------------------------------

  ALTER TABLE "APPS"."T_MEMB_WTHDR_INF" MODIFY ("WTHDR_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_WTHDR_INF" MODIFY ("MEMB_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_WTHDR_INF" MODIFY ("WTHDR_RSN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MEMB_WTHDR_INF" ADD CONSTRAINT "IX_T_MEMB_WTHDR_INF_P" PRIMARY KEY ("WTHDR_SEQ")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_MID_MST
--------------------------------------------------------

  ALTER TABLE "APPS"."T_MID_MST" MODIFY ("MID_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MID_MST" MODIFY ("COMP_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MID_MST" MODIFY ("MID_NAME" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MID_MST" MODIFY ("MID_CODE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MID_MST" MODIFY ("MERCHANT_KEY" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MID_MST" MODIFY ("CURRENCY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MID_MST" MODIFY ("CARD_FEE_RATE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MID_MST" MODIFY ("PG_FEE_RATE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MID_MST" MODIFY ("NICE_FEE_RATE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MID_MST" MODIFY ("FROM_DATE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MID_MST" MODIFY ("TO_DATE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MID_MST" MODIFY ("RGTR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MID_MST" MODIFY ("RGT_DTTM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MID_MST" ADD CONSTRAINT "IX_T_MID_MST_P" PRIMARY KEY ("MID_SEQ")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_MLTLN_MST
--------------------------------------------------------

  ALTER TABLE "APPS"."T_MLTLN_MST" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MLTLN_MST" MODIFY ("CODE_NM_KO" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MLTLN_MST" MODIFY ("CODE_NM_EN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MLTLN_MST" MODIFY ("RGTR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MLTLN_MST" MODIFY ("RGT_DTTM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_MLTLN_MST" ADD CONSTRAINT "IX_T_MLTLN_MST_P" PRIMARY KEY ("CODE")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_POPUP_INF
--------------------------------------------------------

  ALTER TABLE "APPS"."T_POPUP_INF" MODIFY ("POPUP_SEQ" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_POPUP_INF" MODIFY ("POPUP_MST_CD" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_POPUP_INF" MODIFY ("POPUP_NAME" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_POPUP_INF" MODIFY ("CLOSE_OPT" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_POPUP_INF" MODIFY ("CLICKS" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_POPUP_INF" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_POPUP_INF" MODIFY ("DEL_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_POPUP_INF" MODIFY ("RGTR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_POPUP_INF" ADD CONSTRAINT "IX_T_POPUP_INF_P" PRIMARY KEY ("POPUP_SEQ")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_POPUP_MST_INF
--------------------------------------------------------

  ALTER TABLE "APPS"."T_POPUP_MST_INF" MODIFY ("POPUP_MST_CD" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_POPUP_MST_INF" MODIFY ("POPUP_TYPE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_POPUP_MST_INF" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_POPUP_MST_INF" MODIFY ("RGTR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_POPUP_MST_INF" ADD CONSTRAINT "IX_T_POPUP_MST_INF_P" PRIMARY KEY ("POPUP_MST_CD")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_SHORT_URL_INF
--------------------------------------------------------

  ALTER TABLE "APPS"."T_SHORT_URL_INF" MODIFY ("URL_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_SHORT_URL_INF" ADD CONSTRAINT "IX_T_SHORT_URL_INF_P" PRIMARY KEY ("URL_ID")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_SYS_PROP_INF
--------------------------------------------------------

  ALTER TABLE "APPS"."T_SYS_PROP_INF" MODIFY ("SYS_KEY" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_SYS_PROP_INF" MODIFY ("SYS_VALUE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_SYS_PROP_INF" MODIFY ("RGTR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_SYS_PROP_INF" MODIFY ("RGT_DTTM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_SYS_PROP_INF" MODIFY ("CHNR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_SYS_PROP_INF" MODIFY ("CHNG_DTTM" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_SYS_PROP_INF" ADD CONSTRAINT "IX_T_SYS_PROP_INF_P" PRIMARY KEY ("SYS_KEY")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_TERMS_INF
--------------------------------------------------------

  ALTER TABLE "APPS"."T_TERMS_INF" MODIFY ("TERMS_CD" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_TERMS_INF" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_TERMS_INF" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_TERMS_INF" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_TERMS_INF" MODIFY ("REQUIRED_YN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_TERMS_INF" MODIFY ("FROM_DATE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_TERMS_INF" MODIFY ("TO_DATE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_TERMS_INF" MODIFY ("RGTR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."T_TERMS_INF" ADD CONSTRAINT "IX_T_TERMS_INF_P" PRIMARY KEY ("TERMS_CD", "VERSION")
  USING INDEX
  TABLESPACE "TSD_APPS_DEFT"  ENABLE;
